/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ni_DAQmxBase_BaseAnalogMultiChannelReader */

#ifndef _Included_ni_DAQmxBase_BaseAnalogMultiChannelReader
#define _Included_ni_DAQmxBase_BaseAnalogMultiChannelReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ni_DAQmxBase_BaseAnalogMultiChannelReader
 * Method:    readWaveform
 * Signature: (II)[Lni/DAQcommon/AnalogWaveform;
 */
JNIEXPORT jobjectArray JNICALL Java_ni_DAQmxBase_BaseAnalogMultiChannelReader_readWaveform
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ni_DAQmxBase_BaseAnalogMultiChannelReader
 * Method:    readMultiSample
 * Signature: (I)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_ni_DAQmxBase_BaseAnalogMultiChannelReader_readMultiSample
  (JNIEnv *, jobject, jint);

/*
 * Class:     ni_DAQmxBase_BaseAnalogMultiChannelReader
 * Method:    readSingleSample
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ni_DAQmxBase_BaseAnalogMultiChannelReader_readSingleSample
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
