/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ni_DAQmxBase_BaseAnalogMultiChannelReader_ZZReader */

#ifndef _Included_ni_DAQmxBase_BaseAnalogMultiChannelReader_ZZReader
#define _Included_ni_DAQmxBase_BaseAnalogMultiChannelReader_ZZReader
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
