/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ni_DAQmxBase_BaseDaqStream */

#ifndef _Included_ni_DAQmxBase_BaseDaqStream
#define _Included_ni_DAQmxBase_BaseDaqStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ni_DAQmxBase_BaseDaqStream
 * Method:    configureInputBuffer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ni_DAQmxBase_BaseDaqStream_configureInputBuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ni_DAQmxBase_BaseDaqStream
 * Method:    configureOutputBuffer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ni_DAQmxBase_BaseDaqStream_configureOutputBuffer
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
