/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ni_DAQmxBase_BaseLocal */

#ifndef _Included_ni_DAQmxBase_BaseLocal
#define _Included_ni_DAQmxBase_BaseLocal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ni_DAQmxBase_BaseLocal
 * Method:    _init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ni_DAQmxBase_BaseLocal__1init
  (JNIEnv *, jobject);

/*
 * Class:     ni_DAQmxBase_BaseLocal
 * Method:    getPhysicalChannels
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ni_DAQmxBase_BaseLocal_getPhysicalChannels
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
