/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ni_DAQmxBase_BaseTask */

#ifndef _Included_ni_DAQmxBase_BaseTask
#define _Included_ni_DAQmxBase_BaseTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ni_DAQmxBase_BaseTask
 * Method:    createTask
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ni_DAQmxBase_BaseTask_createTask
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ni_DAQmxBase_BaseTask
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ni_DAQmxBase_BaseTask_start
  (JNIEnv *, jobject);

/*
 * Class:     ni_DAQmxBase_BaseTask
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ni_DAQmxBase_BaseTask_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
