/*
 * File:   dices_rc_driver.h
 * Author: Robert England
 *
 * Return codes for base driver tool
 *
 * Created on November 17, 2014
 * Last Modified on November 17, 2014
 */

#ifndef DICES_RC_DRIVER_H_
#define	DICES_RC_DRIVER_H_

#include <string>

enum class DicesRcDriver
{
  OK = 0,
  FAIL = 1,
  // TODO: Seems to only be used for null parameters right now.  Rename after
  // confirming.
  BAD_FUNCTION_ARGUMENT,

  RECONFIGURE_PORT_SETTINGS,

  COMMAND_BUFFER_ALLOCATION_FAILURE,
  RESPONSE_BUFFER_ALLOCATION_FAILURE,
  ORIGIN_TOO_LONG_FAILURE,
  DESTINATION_TOO_SHORT_FAILURE,

  DATABASE_CONNECTION_FAILURE,
  DATABASE_READ_TABLE_FAILURE,
  DATABASE_NOT_ENOUGH_TABLE_COLUMNS_FAILURE,
  DATABASE_OCTET_STRING_PARSE_FAILURE,

  ISTRINGSTREAM_EXTRACT_FORMATTED_OUTPUT_FAILURE,
  VECTOR_PUSH_BACK_FAILURE,

  SET_HOST_ID_AND_APP_ID_FAILURE,

  XML_QOS_FILE_LOAD_FAILURE,

  TYPE_REGISTER_FAILURE,

  PARTICIPANT_CREATE_FAILURE,
  PUBLISHER_LOOKUP_FAILURE,
  SUBSCRIBER_LOOKUP_FAILURE,

  PATIENT_IDENTIFICATION_WRITER_LOOKUP_FAILURE,
  PATIENT_IDENTIFICATION_WRITER_NARROW_FAILURE,
  PATIENT_IDENTIFICATION_REQUEST_WRITER_LOOKUP_FAILURE,
  PATIENT_IDENTIFICATION_REQUEST_WRITER_NARROW_FAILURE,
  PATIENT_IDENTIFICATION_REQUEST_READER_LOOKUP_FAILURE,
  PATIENT_IDENTIFICATION_REQUEST_READER_NARROW_FAILURE,
  PATIENT_IDENTIFICATION_REQUEST_READER_LOAN_RETURN_FAILURE,
  PATIENT_IDENTIFICATION_INSTANCE_CREATE_FAILURE,
  PATIENT_IDENTIFICATION_INSTANCE_WRITE_FAILURE,
  PATIENT_IDENTIFICATION_INSTANCE_DELETE_FAILURE,

  PATIENT_DEMOGRAPHICS_WRITER_LOOKUP_FAILURE,
  PATIENT_DEMOGRAPHICS_WRITER_NARROW_FAILURE,
  PATIENT_DEMOGRAPHICS_REQUEST_WRITER_LOOKUP_FAILURE,
  PATIENT_DEMOGRAPHICS_REQUEST_WRITER_NARROW_FAILURE,
  PATIENT_DEMOGRAPHICS_READER_LOOKUP_FAILURE,
  PATIENT_DEMOGRAPHICS_READER_NARROW_FAILURE,
  PATIENT_DEMOGRAPHICS_INSTANCE_CREATE_FAILURE,
  PATIENT_DEMOGRAPHICS_INSTANCE_WRITE_FAILURE,
  PATIENT_DEMOGRAPHICS_INSTANCE_READ_FAILURE,
  PATIENT_DEMOGRAPHICS_INSTANCE_DELETE_FAILURE,

  ALARM_SIGNAL_INSTANCE_CREATE_FAILURE,

  PHYSIOLOGICAL_ALARM_SIGNAL_WRITER_LOOKUP_FAILURE,
  PHYSIOLOGICAL_ALARM_SIGNAL_WRITER_NARROW_FAILURE,
  PHYSIOLOGICAL_ALARM_SIGNAL_INSTANCE_CREATE_FAILURE,
  PHYSIOLOGICAL_ALARM_SIGNAL_INSTANCE_WRITE_FAILURE,
  PHYSIOLOGICAL_ALARM_SIGNAL_INSTANCE_READ_FAILURE,
  PHYSIOLOGICAL_ALARM_SIGNAL_INSTANCE_DELETE_FAILURE,

  TECHNICAL_ALARM_SIGNAL_WRITER_LOOKUP_FAILURE,
  TECHNICAL_ALARM_SIGNAL_WRITER_NARROW_FAILURE,
  TECHNICAL_ALARM_SIGNAL_INSTANCE_CREATE_FAILURE,
  TECHNICAL_ALARM_SIGNAL_INSTANCE_WRITE_FAILURE,
  TECHNICAL_ALARM_SIGNAL_INSTANCE_READ_FAILURE,
  TECHNICAL_ALARM_SIGNAL_INSTANCE_DELETE_FAILURE,

  INFORMATION_SIGNAL_WRITER_LOOKUP_FAILURE,
  INFORMATION_SIGNAL_WRITER_NARROW_FAILURE,
  INFORMATION_SIGNAL_INSTANCE_CREATE_FAILURE,
  INFORMATION_SIGNAL_INSTANCE_WRITE_FAILURE,
  INFORMATION_SIGNAL_INSTANCE_READ_FAILURE,
  INFORMATION_SIGNAL_INSTANCE_DELETE_FAILURE,

  REMINDER_SIGNAL_WRITER_LOOKUP_FAILURE,
  REMINDER_SIGNAL_WRITER_NARROW_FAILURE,
  REMINDER_SIGNAL_INSTANCE_CREATE_FAILURE,
  REMINDER_SIGNAL_INSTANCE_WRITE_FAILURE,
  REMINDER_SIGNAL_INSTANCE_READ_FAILURE,
  REMINDER_SIGNAL_INSTANCE_DELETE_FAILURE,

  ALARM_CONTEXT_INSTANCE_CREATE_FAILURE,

  PHYSIOLOGICAL_ALARM_CONTEXT_WRITER_LOOKUP_FAILURE,
  PHYSIOLOGICAL_ALARM_CONTEXT_WRITER_NARROW_FAILURE,
  PHYSIOLOGICAL_ALARM_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  PHYSIOLOGICAL_ALARM_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  PHYSIOLOGICAL_ALARM_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  PHYSIOLOGICAL_ALARM_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  PHYSIOLOGICAL_ALARM_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  PHYSIOLOGICAL_ALARM_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  PHYSIOLOGICAL_ALARM_CONTEXT_INSTANCE_CREATE_FAILURE,
  PHYSIOLOGICAL_ALARM_CONTEXT_INSTANCE_WRITE_FAILURE,
  PHYSIOLOGICAL_ALARM_CONTEXT_INSTANCE_READ_FAILURE,
  PHYSIOLOGICAL_ALARM_CONTEXT_INSTANCE_DELETE_FAILURE,

  TECHNICAL_ALARM_CONTEXT_WRITER_LOOKUP_FAILURE,
  TECHNICAL_ALARM_CONTEXT_WRITER_NARROW_FAILURE,
  TECHNICAL_ALARM_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  TECHNICAL_ALARM_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  TECHNICAL_ALARM_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  TECHNICAL_ALARM_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  TECHNICAL_ALARM_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  TECHNICAL_ALARM_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  TECHNICAL_ALARM_CONTEXT_INSTANCE_CREATE_FAILURE,
  TECHNICAL_ALARM_CONTEXT_INSTANCE_WRITE_FAILURE,
  TECHNICAL_ALARM_CONTEXT_INSTANCE_READ_FAILURE,
  TECHNICAL_ALARM_CONTEXT_INSTANCE_DELETE_FAILURE,

  DSA_MEAS_CONTEXT_WRITER_LOOKUP_FAILURE,
  DSA_MEAS_CONTEXT_WRITER_NARROW_FAILURE,
  DSA_MEAS_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  DSA_MEAS_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  DSA_MEAS_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  DSA_MEAS_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  DSA_MEAS_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  DSA_MEAS_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  DSA_MEAS_CONTEXT_INSTANCE_CREATE_FAILURE,
  DSA_MEAS_CONTEXT_INSTANCE_WRITE_FAILURE,
  DSA_MEAS_CONTEXT_INSTANCE_READ_FAILURE,
  DSA_MEAS_CONTEXT_INSTANCE_DELETE_FAILURE,

  DSA_MEAS_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE,
  DSA_MEAS_OBSERVED_VALUE_WRITER_NARROW_FAILURE,
  DSA_MEAS_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,
  DSA_MEAS_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE,
  DSA_MEAS_OBSERVED_VALUE_INSTANCE_READ_FAILURE,
  DSA_MEAS_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE,

  DSA_CALC_CONTEXT_WRITER_LOOKUP_FAILURE,
  DSA_CALC_CONTEXT_WRITER_NARROW_FAILURE,
  DSA_CALC_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  DSA_CALC_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  DSA_CALC_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  DSA_CALC_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  DSA_CALC_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  DSA_CALC_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  DSA_CALC_CONTEXT_INSTANCE_CREATE_FAILURE,
  DSA_CALC_CONTEXT_INSTANCE_WRITE_FAILURE,
  DSA_CALC_CONTEXT_INSTANCE_READ_FAILURE,
  DSA_CALC_CONTEXT_INSTANCE_DELETE_FAILURE,

  DSA_CALC_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE,
  DSA_CALC_OBSERVED_VALUE_WRITER_NARROW_FAILURE,
  DSA_CALC_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,
  DSA_CALC_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE,
  DSA_CALC_OBSERVED_VALUE_INSTANCE_READ_FAILURE,
  DSA_CALC_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE,

  DSA_SETT_CONTEXT_WRITER_LOOKUP_FAILURE,
  DSA_SETT_CONTEXT_WRITER_NARROW_FAILURE,
  DSA_SETT_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  DSA_SETT_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  DSA_SETT_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  DSA_SETT_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  DSA_SETT_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  DSA_SETT_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  DSA_SETT_CONTEXT_INSTANCE_CREATE_FAILURE,
  DSA_SETT_CONTEXT_INSTANCE_WRITE_FAILURE,
  DSA_SETT_CONTEXT_INSTANCE_READ_FAILURE,
  DSA_SETT_CONTEXT_INSTANCE_DELETE_FAILURE,

  DSA_SETT_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE,
  DSA_SETT_OBSERVED_VALUE_WRITER_NARROW_FAILURE,
  DSA_SETT_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,
  DSA_SETT_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE,
  DSA_SETT_OBSERVED_VALUE_INSTANCE_READ_FAILURE,
  DSA_SETT_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE,

  ENUMERATION_CONTEXT_INSTANCE_CREATE_FAILURE,
  ENUMERATION_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,

  ENUMERATION_MEAS_CONTEXT_WRITER_LOOKUP_FAILURE,
  ENUMERATION_MEAS_CONTEXT_WRITER_NARROW_FAILURE,
  ENUMERATION_MEAS_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  ENUMERATION_MEAS_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  ENUMERATION_MEAS_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  ENUMERATION_MEAS_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  ENUMERATION_MEAS_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  ENUMERATION_MEAS_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  ENUMERATION_MEAS_CONTEXT_INSTANCE_CREATE_FAILURE,
  ENUMERATION_MEAS_CONTEXT_INSTANCE_WRITE_FAILURE,
  ENUMERATION_MEAS_CONTEXT_INSTANCE_READ_FAILURE,
  ENUMERATION_MEAS_CONTEXT_INSTANCE_DELETE_FAILURE,

  ENUMERATION_MEAS_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE,
  ENUMERATION_MEAS_OBSERVED_VALUE_WRITER_NARROW_FAILURE,
  ENUMERATION_MEAS_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,
  ENUMERATION_MEAS_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE,
  ENUMERATION_MEAS_OBSERVED_VALUE_INSTANCE_READ_FAILURE,
  ENUMERATION_MEAS_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE,

  ENUMERATION_CALC_CONTEXT_WRITER_LOOKUP_FAILURE,
  ENUMERATION_CALC_CONTEXT_WRITER_NARROW_FAILURE,
  ENUMERATION_CALC_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  ENUMERATION_CALC_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  ENUMERATION_CALC_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  ENUMERATION_CALC_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  ENUMERATION_CALC_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  ENUMERATION_CALC_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  ENUMERATION_CALC_CONTEXT_INSTANCE_CREATE_FAILURE,
  ENUMERATION_CALC_CONTEXT_INSTANCE_WRITE_FAILURE,
  ENUMERATION_CALC_CONTEXT_INSTANCE_READ_FAILURE,
  ENUMERATION_CALC_CONTEXT_INSTANCE_DELETE_FAILURE,

  ENUMERATION_CALC_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE,
  ENUMERATION_CALC_OBSERVED_VALUE_WRITER_NARROW_FAILURE,
  ENUMERATION_CALC_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,
  ENUMERATION_CALC_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE,
  ENUMERATION_CALC_OBSERVED_VALUE_INSTANCE_READ_FAILURE,
  ENUMERATION_CALC_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE,

  ENUMERATION_SETT_CONTEXT_WRITER_LOOKUP_FAILURE,
  ENUMERATION_SETT_CONTEXT_WRITER_NARROW_FAILURE,
  ENUMERATION_SETT_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  ENUMERATION_SETT_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  ENUMERATION_SETT_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  ENUMERATION_SETT_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  ENUMERATION_SETT_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  ENUMERATION_SETT_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  ENUMERATION_SETT_CONTEXT_INSTANCE_CREATE_FAILURE,
  ENUMERATION_SETT_CONTEXT_INSTANCE_WRITE_FAILURE,
  ENUMERATION_SETT_CONTEXT_INSTANCE_READ_FAILURE,
  ENUMERATION_SETT_CONTEXT_INSTANCE_DELETE_FAILURE,

  ENUMERATION_SETT_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE,
  ENUMERATION_SETT_OBSERVED_VALUE_WRITER_NARROW_FAILURE,
  ENUMERATION_SETT_OBSERVED_VALUE_REQUEST_READER_LOOKUP_FAILURE,
  ENUMERATION_SETT_OBSERVED_VALUE_REQUEST_READER_NARROW_FAILURE,
  ENUMERATION_SETT_OBSERVED_VALUE_REQUEST_READER_LOAN_RETURN_FAILURE,
  ENUMERATION_SETT_OBSERVED_VALUE_REQUEST_TOPIC_LOOKUP_FAILURE,
  ENUMERATION_SETT_OBSERVED_VALUE_REQUEST_TOPIC_NARROW_FAILURE,
  ENUMERATION_SETT_OBSERVED_VALUE_REQUEST_TOPIC_FILTER_FAILURE,
  ENUMERATION_SETT_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,
  ENUMERATION_SETT_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE,
  ENUMERATION_SETT_OBSERVED_VALUE_INSTANCE_READ_FAILURE,
  ENUMERATION_SETT_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE,

  MDS_WRITER_LOOKUP_FAILURE,
  MDS_WRITER_NARROW_FAILURE,
  MDS_INSTANCE_CREATE_FAILURE,
  MDS_INSTANCE_WRITE_FAILURE,
  MDS_INSTANCE_READ_FAILURE,
  MDS_INSTANCE_DELETE_FAILURE,

  VMD_WRITER_LOOKUP_FAILURE,
  VMD_WRITER_NARROW_FAILURE,
  VMD_INSTANCE_CREATE_FAILURE,
  VMD_INSTANCE_WRITE_FAILURE,
  VMD_INSTANCE_READ_FAILURE,
  VMD_INSTANCE_DELETE_FAILURE,

  NUMERIC_CONTEXT_INSTANCE_CREATE_FAILURE,
  NUMERIC_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,

  NUMERIC_MEAS_CONTEXT_WRITER_LOOKUP_FAILURE,
  NUMERIC_MEAS_CONTEXT_WRITER_NARROW_FAILURE,
  NUMERIC_MEAS_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  NUMERIC_MEAS_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  NUMERIC_MEAS_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  NUMERIC_MEAS_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  NUMERIC_MEAS_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  NUMERIC_MEAS_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  NUMERIC_MEAS_CONTEXT_INSTANCE_CREATE_FAILURE,
  NUMERIC_MEAS_CONTEXT_INSTANCE_WRITE_FAILURE,
  NUMERIC_MEAS_CONTEXT_INSTANCE_READ_FAILURE,
  NUMERIC_MEAS_CONTEXT_INSTANCE_DELETE_FAILURE,

  NUMERIC_MEAS_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE,
  NUMERIC_MEAS_OBSERVED_VALUE_WRITER_NARROW_FAILURE,
  NUMERIC_MEAS_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,
  NUMERIC_MEAS_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE,
  NUMERIC_MEAS_OBSERVED_VALUE_INSTANCE_READ_FAILURE,
  NUMERIC_MEAS_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE,

  NUMERIC_CALC_CONTEXT_WRITER_LOOKUP_FAILURE,
  NUMERIC_CALC_CONTEXT_WRITER_NARROW_FAILURE,
  NUMERIC_CALC_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  NUMERIC_CALC_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  NUMERIC_CALC_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  NUMERIC_CALC_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  NUMERIC_CALC_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  NUMERIC_CALC_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  NUMERIC_CALC_CONTEXT_INSTANCE_CREATE_FAILURE,
  NUMERIC_CALC_CONTEXT_INSTANCE_WRITE_FAILURE,
  NUMERIC_CALC_CONTEXT_INSTANCE_READ_FAILURE,
  NUMERIC_CALC_CONTEXT_INSTANCE_DELETE_FAILURE,

  NUMERIC_CALC_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE,
  NUMERIC_CALC_OBSERVED_VALUE_WRITER_NARROW_FAILURE,
  NUMERIC_CALC_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,
  NUMERIC_CALC_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE,
  NUMERIC_CALC_OBSERVED_VALUE_INSTANCE_READ_FAILURE,
  NUMERIC_CALC_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE,

  NUMERIC_SETT_CONTEXT_WRITER_LOOKUP_FAILURE,
  NUMERIC_SETT_CONTEXT_WRITER_NARROW_FAILURE,
  NUMERIC_SETT_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  NUMERIC_SETT_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  NUMERIC_SETT_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  NUMERIC_SETT_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  NUMERIC_SETT_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  NUMERIC_SETT_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  NUMERIC_SETT_CONTEXT_INSTANCE_CREATE_FAILURE,
  NUMERIC_SETT_CONTEXT_INSTANCE_WRITE_FAILURE,
  NUMERIC_SETT_CONTEXT_INSTANCE_READ_FAILURE,
  NUMERIC_SETT_CONTEXT_INSTANCE_DELETE_FAILURE,

  NUMERIC_SETT_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE,
  NUMERIC_SETT_OBSERVED_VALUE_WRITER_NARROW_FAILURE,
  NUMERIC_SETT_OBSERVED_VALUE_REQUEST_READER_LOOKUP_FAILURE,
  NUMERIC_SETT_OBSERVED_VALUE_REQUEST_READER_NARROW_FAILURE,
  NUMERIC_SETT_OBSERVED_VALUE_REQUEST_READER_LOAN_RETURN_FAILURE,
  NUMERIC_SETT_OBSERVED_VALUE_REQUEST_TOPIC_LOOKUP_FAILURE,
  NUMERIC_SETT_OBSERVED_VALUE_REQUEST_TOPIC_NARROW_FAILURE,
  NUMERIC_SETT_OBSERVED_VALUE_REQUEST_TOPIC_FILTER_FAILURE,
  NUMERIC_SETT_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,
  NUMERIC_SETT_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE,
  NUMERIC_SETT_OBSERVED_VALUE_INSTANCE_READ_FAILURE,
  NUMERIC_SETT_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE,

  RTSA_CONTEXT_INSTANCE_CREATE_FAILURE,
  RTSA_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,

  RTSA_MEAS_CONTEXT_WRITER_LOOKUP_FAILURE,
  RTSA_MEAS_CONTEXT_WRITER_NARROW_FAILURE,
  RTSA_MEAS_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  RTSA_MEAS_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  RTSA_MEAS_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  RTSA_MEAS_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  RTSA_MEAS_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  RTSA_MEAS_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  RTSA_MEAS_CONTEXT_INSTANCE_CREATE_FAILURE,
  RTSA_MEAS_CONTEXT_INSTANCE_WRITE_FAILURE,
  RTSA_MEAS_CONTEXT_INSTANCE_READ_FAILURE,
  RTSA_MEAS_CONTEXT_INSTANCE_DELETE_FAILURE,

  RTSA_MEAS_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE,
  RTSA_MEAS_OBSERVED_VALUE_WRITER_NARROW_FAILURE,
  RTSA_MEAS_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,
  RTSA_MEAS_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE,
  RTSA_MEAS_OBSERVED_VALUE_INSTANCE_READ_FAILURE,
  RTSA_MEAS_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE,

  RTSA_CALC_CONTEXT_WRITER_LOOKUP_FAILURE,
  RTSA_CALC_CONTEXT_WRITER_NARROW_FAILURE,
  RTSA_CALC_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  RTSA_CALC_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  RTSA_CALC_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  RTSA_CALC_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  RTSA_CALC_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  RTSA_CALC_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  RTSA_CALC_CONTEXT_INSTANCE_CREATE_FAILURE,
  RTSA_CALC_CONTEXT_INSTANCE_WRITE_FAILURE,
  RTSA_CALC_CONTEXT_INSTANCE_READ_FAILURE,
  RTSA_CALC_CONTEXT_INSTANCE_DELETE_FAILURE,

  RTSA_CALC_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE,
  RTSA_CALC_OBSERVED_VALUE_WRITER_NARROW_FAILURE,
  RTSA_CALC_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,
  RTSA_CALC_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE,
  RTSA_CALC_OBSERVED_VALUE_INSTANCE_READ_FAILURE,
  RTSA_CALC_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE,

  RTSA_SETT_CONTEXT_WRITER_LOOKUP_FAILURE,
  RTSA_SETT_CONTEXT_WRITER_NARROW_FAILURE,
  RTSA_SETT_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  RTSA_SETT_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  RTSA_SETT_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  RTSA_SETT_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  RTSA_SETT_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  RTSA_SETT_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  RTSA_SETT_CONTEXT_INSTANCE_CREATE_FAILURE,
  RTSA_SETT_CONTEXT_INSTANCE_WRITE_FAILURE,
  RTSA_SETT_CONTEXT_INSTANCE_READ_FAILURE,
  RTSA_SETT_CONTEXT_INSTANCE_DELETE_FAILURE,

  RTSA_SETT_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE,
  RTSA_SETT_OBSERVED_VALUE_WRITER_NARROW_FAILURE,
  RTSA_SETT_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,
  RTSA_SETT_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE,
  RTSA_SETT_OBSERVED_VALUE_INSTANCE_READ_FAILURE,
  RTSA_SETT_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE,

  TSA_MEAS_CONTEXT_WRITER_LOOKUP_FAILURE,
  TSA_MEAS_CONTEXT_WRITER_NARROW_FAILURE,
  TSA_MEAS_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  TSA_MEAS_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  TSA_MEAS_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  TSA_MEAS_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  TSA_MEAS_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  TSA_MEAS_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  TSA_MEAS_CONTEXT_INSTANCE_CREATE_FAILURE,
  TSA_MEAS_CONTEXT_INSTANCE_WRITE_FAILURE,
  TSA_MEAS_CONTEXT_INSTANCE_READ_FAILURE,
  TSA_MEAS_CONTEXT_INSTANCE_DELETE_FAILURE,

  TSA_MEAS_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE,
  TSA_MEAS_OBSERVED_VALUE_WRITER_NARROW_FAILURE,
  TSA_MEAS_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,
  TSA_MEAS_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE,
  TSA_MEAS_OBSERVED_VALUE_INSTANCE_READ_FAILURE,
  TSA_MEAS_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE,

  TSA_CALC_CONTEXT_WRITER_LOOKUP_FAILURE,
  TSA_CALC_CONTEXT_WRITER_NARROW_FAILURE,
  TSA_CALC_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  TSA_CALC_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  TSA_CALC_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  TSA_CALC_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  TSA_CALC_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  TSA_CALC_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  TSA_CALC_CONTEXT_INSTANCE_CREATE_FAILURE,
  TSA_CALC_CONTEXT_INSTANCE_WRITE_FAILURE,
  TSA_CALC_CONTEXT_INSTANCE_READ_FAILURE,
  TSA_CALC_CONTEXT_INSTANCE_DELETE_FAILURE,

  TSA_CALC_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE,
  TSA_CALC_OBSERVED_VALUE_WRITER_NARROW_FAILURE,
  TSA_CALC_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,
  TSA_CALC_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE,
  TSA_CALC_OBSERVED_VALUE_INSTANCE_READ_FAILURE,
  TSA_CALC_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE,

  TSA_SETT_CONTEXT_WRITER_LOOKUP_FAILURE,
  TSA_SETT_CONTEXT_WRITER_NARROW_FAILURE,
  TSA_SETT_CONTEXT_REQUEST_READER_LOOKUP_FAILURE,
  TSA_SETT_CONTEXT_REQUEST_READER_NARROW_FAILURE,
  TSA_SETT_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE,
  TSA_SETT_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE,
  TSA_SETT_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE,
  TSA_SETT_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE,
  TSA_SETT_CONTEXT_INSTANCE_CREATE_FAILURE,
  TSA_SETT_CONTEXT_INSTANCE_WRITE_FAILURE,
  TSA_SETT_CONTEXT_INSTANCE_READ_FAILURE,
  TSA_SETT_CONTEXT_INSTANCE_DELETE_FAILURE,

  TSA_SETT_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE,
  TSA_SETT_OBSERVED_VALUE_WRITER_NARROW_FAILURE,
  TSA_SETT_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE,
  TSA_SETT_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE,
  TSA_SETT_OBSERVED_VALUE_INSTANCE_READ_FAILURE,
  TSA_SETT_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE,

  ALLERGY_WRITER_LOOKUP_FAILURE,
  ALLERGY_WRITER_NARROW_FAILURE,
  ALLERGY_READER_LOOKUP_FAILURE,
  ALLERGY_READER_RETURN_LOAN_FAILURE,
  ALLERGY_INSTANCE_CREATE_FAILURE,
  ALLERGY_INSTANCE_WRITE_FAILURE,
  ALLERGY_INSTANCE_READ_FAILURE,
  ALLERGY_INSTANCE_DELETE_FAILURE,
  ALLERGY_READER_NARROW_FAILURE,

  DIAGNOSIS_WRITER_LOOKUP_FAILURE,
  DIAGNOSIS_WRITER_NARROW_FAILURE,
  DIAGNOSIS_INSTANCE_CREATE_FAILURE,
  DIAGNOSIS_INSTANCE_WRITE_FAILURE,
  DIAGNOSIS_INSTANCE_READ_FAILURE,
  DIAGNOSIS_INSTANCE_DELETE_FAILURE,

  DXHISTORY_WRITER_LOOKUP_FAILURE,
  DXHISTORY_WRITER_NARROW_FAILURE,
  DXHISTORY_INSTANCE_CREATE_FAILURE,
  DXHISTORY_INSTANCE_WRITE_FAILURE,
  DXHISTORY_INSTANCE_READ_FAILURE,
  DXHISTORY_INSTANCE_DELETE_FAILURE,

  PATIENT_MEDICATION_WRITER_LOOKUP_FAILURE,
  PATIENT_MEDICATION_WRITER_NARROW_FAILURE,
  PATIENT_MEDICATION_INSTANCE_CREATE_FAILURE,
  PATIENT_MEDICATION_INSTANCE_WRITE_FAILURE,
  PATIENT_MEDICATION_INSTANCE_READ_FAILURE,
  PATIENT_MEDICATION_INSTANCE_DELETE_FAILURE,

  DEVICE_DRIVER_STATE_REQUEST_READER_LOOKUP_FAILURE,
  DEVICE_DRIVER_STATE_REQUEST_READER_NARROW_FAILURE,
  DEVICE_DRIVER_STATE_REQUEST_READER_LOAN_RETURN_FAILURE,
  DEVICE_DRIVER_STATE_REQUEST_TOPIC_LOOKUP_FAILURE,
  DEVICE_DRIVER_STATE_REQUEST_TOPIC_NARROW_FAILURE,
  DEVICE_DRIVER_STATE_REQUEST_TOPIC_FILTER_FAILURE,
  DEVICE_DRIVER_STATE_INSTANCE_CREATE_FAILURE,
  DEVICE_DRIVER_STATE_INSTANCE_WRITE_FAILURE,
  DEVICE_DRIVER_STATE_INSTANCE_READ_FAILURE,
  DEVICE_DRIVER_STATE_INSTANCE_DELETE_FAILURE,

  SET_ICE_ID_FAILURE,

  DRIVER_STATUS_HANDLER_INIT_FAILURE,
  DRIVER_STATUS_CONNECTING_FAILURE,
  DRIVER_STATUS_OPERATING_FAILURE,
  DRIVER_STATUS_SHUTDOWN_FAILURE,
  DRIVER_STATUS_ERROR_FAILURE,
  DRIVER_STATUS_HANDLER_SHUTDOWN_FAILURE,

  DELETE_CONTAINED_ENTITIES_FAILURE,
  DELETE_PARTICIPANT_FAILURE,
  FINALIZE_INSTANCE_FAILURE,

  NO_NEW_DATA,

  HANDSHAKE_DONE,
  QUIT,

  MEMORY_ALLOCATION_FAILURE,

  UNDEFINED_ENUM_VALUE_FAILURE,
  PARAMETER_RANGE_FAILURE,

  GET_RELATIVE_TIME_FAILURE,
  GET_TIME_OF_DAY_UTC_FAILURE,

  BASE_COMM_OPEN_FAILURE,
  BASE_COMM_CLOSE_FAILURE,
  BASE_COMM_SEND_FAILURE,
  BASE_COMM_READ_FAILURE,
  BASE_COMM_FLUSH_FAILURE,

  BASE_COMM_POINTER_IS_NULL,
  PARSER_POINTER_IS_NULL,
  COMMAND_BUFFER_POINTER_IS_NULL,
  RESPONSE_BUFFER_POINTER_IS_NULL,

  READ_TIMEOUT,
  DEVICE_DISCONNECTION,
  
  ERROR_PARSING_JSON_RESPONSE,

  PARSE_RESPONSE_FAILURE
};

class DicesRcDriverStatusMessage
{
 public:

  const static std::string DicesRcDriverToString(const DicesRcDriver error_code)
  {
    std::string code_message;
    switch (error_code)
    {
      case DicesRcDriver::OK:
        code_message = "Ok";
        break;
      case DicesRcDriver::FAIL:
        code_message = "Fail";
        break;
      case DicesRcDriver::BAD_FUNCTION_ARGUMENT:
        code_message = "Bad function argument";
        break;

      case DicesRcDriver::RECONFIGURE_PORT_SETTINGS:
        code_message = "Reconfigure port settings";
        break;

      case DicesRcDriver::COMMAND_BUFFER_ALLOCATION_FAILURE:
        code_message = " Failure allocating memory for parser command buffer.";
        break;
      case DicesRcDriver::RESPONSE_BUFFER_ALLOCATION_FAILURE:
        code_message = " Failure allocating memory for parser response buffer.";
        break;
      case DicesRcDriver::ORIGIN_TOO_LONG_FAILURE:
        code_message = " Origin buffer for set method is longer than max field length.";
        break;
      case DicesRcDriver::DESTINATION_TOO_SHORT_FAILURE:
        code_message = " Destination buffer for get method is shorter than field length.";
        break;

      case DicesRcDriver::DATABASE_CONNECTION_FAILURE:
        code_message = " Failed to get connection from ConnectionFactory";
        break;
      case DicesRcDriver::DATABASE_READ_TABLE_FAILURE:
        code_message = " Failed to execute and commit SQL query which reads "
          "table from a database.";
        break;
      case DicesRcDriver::DATABASE_NOT_ENOUGH_TABLE_COLUMNS_FAILURE:
        code_message = " Failed parse table query response because there are "
          "not enough table columns.";
        break;
      case DicesRcDriver::DATABASE_OCTET_STRING_PARSE_FAILURE:
        code_message = " Failed to parse octet string from database";
        break;

      case DicesRcDriver::ISTRINGSTREAM_EXTRACT_FORMATTED_OUTPUT_FAILURE:
        code_message = " Failed to extract formatted output from istringstream";
        break;
      case DicesRcDriver::VECTOR_PUSH_BACK_FAILURE:
        code_message = " Failed to push back on vector";
        break;

      case DicesRcDriver::SET_HOST_ID_AND_APP_ID_FAILURE:
        code_message = "Failed to set host id and app id for DDS GUID";
        break;

      case DicesRcDriver::XML_QOS_FILE_LOAD_FAILURE:
        code_message = "Failed to load XML Qos configuration file";
        break;

      case DicesRcDriver::TYPE_REGISTER_FAILURE:
        code_message = "Failed to register DDS types";
        break;

      case DicesRcDriver::PARTICIPANT_CREATE_FAILURE:
        code_message = "Failed to create DDS Participant from QoS file";
        break;
      case DicesRcDriver::PUBLISHER_LOOKUP_FAILURE:
        code_message = "Failed to look up DDS Publisher from QoS file";
        break;
      case DicesRcDriver::SUBSCRIBER_LOOKUP_FAILURE:
        code_message = "Failed to look up DDS Subscriber from QoS file";
        break;

      case DicesRcDriver::PATIENT_IDENTIFICATION_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Patient Identification writer from QoS file";
        break;
      case DicesRcDriver::PATIENT_IDENTIFICATION_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Patient Identification writer";
        break;
      case DicesRcDriver::PATIENT_IDENTIFICATION_REQUEST_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Patient Identification Request writer from QoS file";
        break;
      case DicesRcDriver::PATIENT_IDENTIFICATION_REQUEST_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Patient Identification Request writer";
        break;
      case DicesRcDriver::PATIENT_IDENTIFICATION_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up Patient Identification Request reader from QoS file";
        break;
      case DicesRcDriver::PATIENT_IDENTIFICATION_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow Patient Identification Request reader";
        break;
      case DicesRcDriver::PATIENT_IDENTIFICATION_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on Patient Identification Request reader";
        break;
      case DicesRcDriver::PATIENT_IDENTIFICATION_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Patient Identification instance";
        break;
      case DicesRcDriver::PATIENT_IDENTIFICATION_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Patient Identification instance to DDS topic";
        break;
      case DicesRcDriver::PATIENT_IDENTIFICATION_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Patient Identification instance";
        break;

      case DicesRcDriver::PATIENT_DEMOGRAPHICS_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Patient Demographics writer from QoS file";
        break;
      case DicesRcDriver::PATIENT_DEMOGRAPHICS_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Patient Demographics writer";
        break;
      case DicesRcDriver::PATIENT_DEMOGRAPHICS_REQUEST_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Patient Demographics Request writer from QoS file";
        break;
      case DicesRcDriver::PATIENT_DEMOGRAPHICS_REQUEST_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Patient Demographics Request writer";
        break;
      case DicesRcDriver::PATIENT_DEMOGRAPHICS_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up Patient Demographics reader from QoS file";
        break;
      case DicesRcDriver::PATIENT_DEMOGRAPHICS_READER_NARROW_FAILURE:
        code_message = "Failed to narrow Patient Demographics reader";
        break;
      case DicesRcDriver::PATIENT_DEMOGRAPHICS_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Patient Demographics instance";
        break;
      case DicesRcDriver::PATIENT_DEMOGRAPHICS_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Patient Demographics instance to DDS topic";
        break;
      case DicesRcDriver::PATIENT_DEMOGRAPHICS_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Patient Demographics instance from DDS topic";
        break;
      case DicesRcDriver::PATIENT_DEMOGRAPHICS_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Patient Demographics instance";
        break;

      case DicesRcDriver::ALARM_SIGNAL_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Alarm Signal instance";
        break;

      case DicesRcDriver::PHYSIOLOGICAL_ALARM_SIGNAL_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Physiological Alarm Signal writer from QoS file";
        break;
      case DicesRcDriver::PHYSIOLOGICAL_ALARM_SIGNAL_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Physiological Alarm Signal writer";
        break;
      case DicesRcDriver::PHYSIOLOGICAL_ALARM_SIGNAL_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Physiological Alarm Signal instance";
        break;
      case DicesRcDriver::PHYSIOLOGICAL_ALARM_SIGNAL_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Physiological Alarm Signal instance to DDS topic";
        break;
      case DicesRcDriver::PHYSIOLOGICAL_ALARM_SIGNAL_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Physiological Alarm Signal instance from DDS topic";
        break;
      case DicesRcDriver::PHYSIOLOGICAL_ALARM_SIGNAL_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Physiological Alarm Signal instance";
        break;

      case DicesRcDriver::TECHNICAL_ALARM_SIGNAL_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up TECHNICAL Alarm Signal writer from QoS file";
        break;
      case DicesRcDriver::TECHNICAL_ALARM_SIGNAL_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Technical Alarm Signal writer";
        break;
      case DicesRcDriver::TECHNICAL_ALARM_SIGNAL_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Technical Alarm Signal instance";
        break;
      case DicesRcDriver::TECHNICAL_ALARM_SIGNAL_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Technical Alarm Signal instance to DDS topic";
        break;
      case DicesRcDriver::TECHNICAL_ALARM_SIGNAL_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Technical Alarm Signal instance from DDS topic";
        break;
      case DicesRcDriver::TECHNICAL_ALARM_SIGNAL_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Technical Alarm Signal instance";
        break;

      case DicesRcDriver::INFORMATION_SIGNAL_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Information Signal writer from QoS file";
        break;
      case DicesRcDriver::INFORMATION_SIGNAL_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Information Signal writer";
        break;
      case DicesRcDriver::INFORMATION_SIGNAL_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Information Signal instance";
        break;
      case DicesRcDriver::INFORMATION_SIGNAL_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Information Signal instance to DDS topic";
        break;
      case DicesRcDriver::INFORMATION_SIGNAL_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Information Signal instance from DDS topic";
        break;
      case DicesRcDriver::INFORMATION_SIGNAL_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Information Signal instance";
        break;

      case DicesRcDriver::REMINDER_SIGNAL_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Reminder Signal writer from QoS file";
        break;
      case DicesRcDriver::REMINDER_SIGNAL_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Reminder Signal writer";
        break;
      case DicesRcDriver::REMINDER_SIGNAL_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Reminder Signal instance";
        break;
      case DicesRcDriver::REMINDER_SIGNAL_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Reminder Signal instance to DDS topic";
        break;
      case DicesRcDriver::REMINDER_SIGNAL_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Reminder Signal instance from DDS topic";
        break;
      case DicesRcDriver::REMINDER_SIGNAL_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Reminder Signal instance";
        break;

      case DicesRcDriver::ALARM_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Alarm Context instance";
        break;

      case DicesRcDriver::PHYSIOLOGICAL_ALARM_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Physiological Alarm Context writer from QoS file";
        break;
      case DicesRcDriver::PHYSIOLOGICAL_ALARM_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Physiological Alarm Context writer";
        break;
      case DicesRcDriver::PHYSIOLOGICAL_ALARM_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up Physiological Alarm Context Request reader from QoS file";
        break;
      case DicesRcDriver::PHYSIOLOGICAL_ALARM_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow Physiological Alarm Context Request reader";
        break;
      case DicesRcDriver::PHYSIOLOGICAL_ALARM_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on Physiological Alarm Context Request reader";
        break;
      case DicesRcDriver::PHYSIOLOGICAL_ALARM_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up Physiological Alarm Context Request topic from QoS file";
        break;
      case DicesRcDriver::PHYSIOLOGICAL_ALARM_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow Physiological Alarm Context Request topic";
        break;
      case DicesRcDriver::PHYSIOLOGICAL_ALARM_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set Physiological Alarm Context Request topic content filter";
        break;
      case DicesRcDriver::PHYSIOLOGICAL_ALARM_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Physiological Alarm Context instance";
        break;
      case DicesRcDriver::PHYSIOLOGICAL_ALARM_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Physiological Alarm Context instance to DDS topic";
        break;
      case DicesRcDriver::PHYSIOLOGICAL_ALARM_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Physiological Alarm Context instance from DDS topic";
        break;
      case DicesRcDriver::PHYSIOLOGICAL_ALARM_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Physiological Alarm Context instance";
        break;

      case DicesRcDriver::TECHNICAL_ALARM_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Technical Alarm Context writer from QoS file";
        break;
      case DicesRcDriver::TECHNICAL_ALARM_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Technical Alarm Context writer";
        break;
      case DicesRcDriver::TECHNICAL_ALARM_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up Technical Alarm Context Request reader from QoS file";
        break;
      case DicesRcDriver::TECHNICAL_ALARM_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow Technical Alarm Context Request reader";
        break;
      case DicesRcDriver::TECHNICAL_ALARM_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on Technical Alarm Context Request reader";
        break;
      case DicesRcDriver::TECHNICAL_ALARM_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up Technical Alarm Context Request topic from QoS file";
        break;
      case DicesRcDriver::TECHNICAL_ALARM_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow Technical Alarm Context Request topic";
        break;
      case DicesRcDriver::TECHNICAL_ALARM_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set Technical Alarm Context Request topic content filter";
        break;
      case DicesRcDriver::TECHNICAL_ALARM_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Technical Alarm Context instance";
        break;
      case DicesRcDriver::TECHNICAL_ALARM_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Technical Alarm Context instance to DDS topic";
        break;
      case DicesRcDriver::TECHNICAL_ALARM_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Technical Alarm Context instance from DDS topic";
        break;
      case DicesRcDriver::TECHNICAL_ALARM_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Technical Alarm Context instance";
        break;

      case DicesRcDriver::DSA_MEAS_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up DSA Measured Context writer from QoS file";
        break;
      case DicesRcDriver::DSA_MEAS_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow DSA Measured Context writer";
        break;
      case DicesRcDriver::DSA_MEAS_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up DSA Measured Context Request reader from QoS file";
        break;
      case DicesRcDriver::DSA_MEAS_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow DSA Measured Context Request reader";
        break;
      case DicesRcDriver::DSA_MEAS_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on DSA Measured Context Request reader";
        break;
      case DicesRcDriver::DSA_MEAS_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up DSA Measured Context Request topic from QoS file";
        break;
      case DicesRcDriver::DSA_MEAS_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow DSA Measured Context Request topic";
        break;
      case DicesRcDriver::DSA_MEAS_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set DSA Measured Context Request topic content filter";
        break;
      case DicesRcDriver::DSA_MEAS_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create DSA Measured Context instance";
        break;
      case DicesRcDriver::DSA_MEAS_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write DSA Measured Context instance to DDS topic";
        break;
      case DicesRcDriver::DSA_MEAS_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read DSA Measured Context instance from DDS topic";
        break;
      case DicesRcDriver::DSA_MEAS_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete DSA Measured Context instance";
        break;

      case DicesRcDriver::DSA_MEAS_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up DSA Measured Observed Value writer from QoS file";
        break;
      case DicesRcDriver::DSA_MEAS_OBSERVED_VALUE_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow DSA Measured Observed Value writer";
        break;
      case DicesRcDriver::DSA_MEAS_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create DSA Measured Observed Value instance";
        break;
      case DicesRcDriver::DSA_MEAS_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write DSA Measured Observed Value instance to DDS topic";
        break;
      case DicesRcDriver::DSA_MEAS_OBSERVED_VALUE_INSTANCE_READ_FAILURE:
        code_message = "Failed to read DSA Measured Observed Value instance from DDS topic";
        break;
      case DicesRcDriver::DSA_MEAS_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete DSA Measured Observed Value instance";
        break;

      case DicesRcDriver::DSA_CALC_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up DSA Calculated Context writer from QoS file";
        break;
      case DicesRcDriver::DSA_CALC_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow DSA Calculated Context writer";
        break;
      case DicesRcDriver::DSA_CALC_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up DSA Calculated Context Request reader from QoS file";
        break;
      case DicesRcDriver::DSA_CALC_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow DSA Calculated Context Request reader";
        break;
      case DicesRcDriver::DSA_CALC_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on DSA Calculated Context Request reader";
        break;
      case DicesRcDriver::DSA_CALC_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up DSA Calculated Context Request topic from QoS file";
        break;
      case DicesRcDriver::DSA_CALC_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow DSA Calculated Context Request topic";
        break;
      case DicesRcDriver::DSA_CALC_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set DSA Calculated Context Request topic content filter";
        break;
      case DicesRcDriver::DSA_CALC_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create DSA Calculated Context instance";
        break;
      case DicesRcDriver::DSA_CALC_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write DSA Calculated Context instance to DDS topic";
        break;
      case DicesRcDriver::DSA_CALC_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read DSA Calculated Context instance from DDS topic";
        break;
      case DicesRcDriver::DSA_CALC_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete DSA Calculated Context instance";
        break;

      case DicesRcDriver::DSA_CALC_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up DSA Calculated Observed Value writer from QoS file";
        break;
      case DicesRcDriver::DSA_CALC_OBSERVED_VALUE_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow DSA Calculated Observed Value writer";
        break;
      case DicesRcDriver::DSA_CALC_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create DSA Calculated Observed Value instance";
        break;
      case DicesRcDriver::DSA_CALC_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write DSA Calculated Observed Value instance to DDS topic";
        break;
      case DicesRcDriver::DSA_CALC_OBSERVED_VALUE_INSTANCE_READ_FAILURE:
        code_message = "Failed to read DSA Calculated Observed Value instance from DDS topic";
        break;
      case DicesRcDriver::DSA_CALC_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete DSA Calculated Observed Value instance";
        break;

      case DicesRcDriver::DSA_SETT_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up DSA Setting Context writer from QoS file";
        break;
      case DicesRcDriver::DSA_SETT_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow DSA Setting Context writer";
        break;
      case DicesRcDriver::DSA_SETT_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up DSA Setting Context Request reader from QoS file";
        break;
      case DicesRcDriver::DSA_SETT_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow DSA Setting Context Request reader";
        break;
      case DicesRcDriver::DSA_SETT_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on DSA Setting Context Request reader";
        break;
      case DicesRcDriver::DSA_SETT_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up DSA Setting Context Request topic from QoS file";
        break;
      case DicesRcDriver::DSA_SETT_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow DSA Setting Context Request topic";
        break;
      case DicesRcDriver::DSA_SETT_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set DSA Setting Context Request topic content filter";
        break;
      case DicesRcDriver::DSA_SETT_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create DSA Setting Context instance";
        break;
      case DicesRcDriver::DSA_SETT_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write DSA Setting Context instance to DDS topic";
        break;
      case DicesRcDriver::DSA_SETT_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read DSA Setting Context instance from DDS topic";
        break;
      case DicesRcDriver::DSA_SETT_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete DSA Setting Context instance";
        break;

      case DicesRcDriver::DSA_SETT_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up DSA Setting Observed Value writer from QoS file";
        break;
      case DicesRcDriver::DSA_SETT_OBSERVED_VALUE_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow DSA Setting Observed Value writer";
        break;
      case DicesRcDriver::DSA_SETT_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create DSA Setting Observed Value instance";
        break;
      case DicesRcDriver::DSA_SETT_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write DSA Setting Observed Value instance to DDS topic";
        break;
      case DicesRcDriver::DSA_SETT_OBSERVED_VALUE_INSTANCE_READ_FAILURE:
        code_message = "Failed to read DSA Setting Observed Value instance from DDS topic";
        break;
      case DicesRcDriver::DSA_SETT_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete DSA Setting Observed Value instance";
        break;

      case DicesRcDriver::ENUMERATION_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Enumeration Context instance";
        break;
      case DicesRcDriver::ENUMERATION_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Enumeration Observed Value instance";
        break;

      case DicesRcDriver::ENUMERATION_MEAS_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Enumeration Measured Context writer from QoS file";
        break;
      case DicesRcDriver::ENUMERATION_MEAS_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Enumeration Measured Context writer";
        break;
      case DicesRcDriver::ENUMERATION_MEAS_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up Enumeration Measured Context Request reader from QoS file";
        break;
      case DicesRcDriver::ENUMERATION_MEAS_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow Enumeration Measured Context Request reader";
        break;
      case DicesRcDriver::ENUMERATION_MEAS_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on Enumeration Measured Context Request reader";
        break;
      case DicesRcDriver::ENUMERATION_MEAS_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up Enumeration Measured Context Request topic from QoS file";
        break;
      case DicesRcDriver::ENUMERATION_MEAS_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow Enumeration Measured Context Request topic";
        break;
      case DicesRcDriver::ENUMERATION_MEAS_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set Enumeration Measured Context Request topic content filter";
        break;
      case DicesRcDriver::ENUMERATION_MEAS_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Enumeration Measured Context instance";
        break;
      case DicesRcDriver::ENUMERATION_MEAS_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Enumeration Measured Context instance to DDS topic";
        break;
      case DicesRcDriver::ENUMERATION_MEAS_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Enumeration Measured Context instance from DDS topic";
        break;
      case DicesRcDriver::ENUMERATION_MEAS_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Enumeration Measured Context instance";
        break;

      case DicesRcDriver::ENUMERATION_MEAS_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Enumeration Measured Observed Value writer from QoS file";
        break;
      case DicesRcDriver::ENUMERATION_MEAS_OBSERVED_VALUE_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Enumeration Measured Observed Value writer";
        break;
      case DicesRcDriver::ENUMERATION_MEAS_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Enumeration Measured Observed Value instance";
        break;
      case DicesRcDriver::ENUMERATION_MEAS_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Enumeration Measured Observed Value instance to DDS topic";
        break;
      case DicesRcDriver::ENUMERATION_MEAS_OBSERVED_VALUE_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Enumeration Measured Observed Value instance from DDS topic";
        break;
      case DicesRcDriver::ENUMERATION_MEAS_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Enumeration Measured Observed Value instance";
        break;

      case DicesRcDriver::ENUMERATION_CALC_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Enumeration Calculated Context writer from QoS file";
        break;
      case DicesRcDriver::ENUMERATION_CALC_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Enumeration Calculated Context writer";
        break;
      case DicesRcDriver::ENUMERATION_CALC_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up Enumeration Calculated Context Request reader from QoS file";
        break;
      case DicesRcDriver::ENUMERATION_CALC_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow Enumeration Calculated Context Request reader";
        break;
      case DicesRcDriver::ENUMERATION_CALC_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on Enumeration Calculated Context Request reader";
        break;
      case DicesRcDriver::ENUMERATION_CALC_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up Enumeration Calculated Context Request topic from QoS file";
        break;
      case DicesRcDriver::ENUMERATION_CALC_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow Enumeration Calculated Context Request topic";
        break;
      case DicesRcDriver::ENUMERATION_CALC_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set Enumeration Calculated Context Request topic content filter";
        break;
      case DicesRcDriver::ENUMERATION_CALC_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Enumeration Calculated Context instance";
        break;
      case DicesRcDriver::ENUMERATION_CALC_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Enumeration Calculated Context instance to DDS topic";
        break;
      case DicesRcDriver::ENUMERATION_CALC_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Enumeration Calculated Context instance from DDS topic";
        break;
      case DicesRcDriver::ENUMERATION_CALC_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Enumeration Calculated Context instance";
        break;

      case DicesRcDriver::ENUMERATION_CALC_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Enumeration Calculated Observed Value writer from QoS file";
        break;
      case DicesRcDriver::ENUMERATION_CALC_OBSERVED_VALUE_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Enumeration Calculated Observed Value writer";
        break;
      case DicesRcDriver::ENUMERATION_CALC_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Enumeration Calculated Observed Value instance";
        break;
      case DicesRcDriver::ENUMERATION_CALC_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Enumeration Calculated Observed Value instance to DDS topic";
        break;
      case DicesRcDriver::ENUMERATION_CALC_OBSERVED_VALUE_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Enumeration Calculated Observed Value instance from DDS topic";
        break;
      case DicesRcDriver::ENUMERATION_CALC_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Enumeration Calculated Observed Value instance";
        break;

      case DicesRcDriver::ENUMERATION_SETT_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Enumeration Setting Context writer from QoS file";
        break;
      case DicesRcDriver::ENUMERATION_SETT_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Enumeration Setting Context writer";
        break;
      case DicesRcDriver::ENUMERATION_SETT_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up Enumeration Setting Context Request reader from QoS file";
        break;
      case DicesRcDriver::ENUMERATION_SETT_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow Enumeration Setting Context Request reader";
        break;
      case DicesRcDriver::ENUMERATION_SETT_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on Enumeration Setting Context Request reader";
        break;
      case DicesRcDriver::ENUMERATION_SETT_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up Enumeration Setting Context Request topic from QoS file";
        break;
      case DicesRcDriver::ENUMERATION_SETT_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow Enumeration Setting Context Request topic";
        break;
      case DicesRcDriver::ENUMERATION_SETT_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set Enumeration Setting Context Request topic content filter";
        break;
      case DicesRcDriver::ENUMERATION_SETT_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Enumeration Setting Context instance";
        break;
      case DicesRcDriver::ENUMERATION_SETT_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Enumeration Setting Context instance to DDS topic";
        break;
      case DicesRcDriver::ENUMERATION_SETT_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Enumeration Setting Context instance from DDS topic";
        break;
      case DicesRcDriver::ENUMERATION_SETT_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Enumeration Setting Context instance";
        break;

      case DicesRcDriver::ENUMERATION_SETT_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Enumeration Setting Observed Value writer from QoS file";
        break;
      case DicesRcDriver::ENUMERATION_SETT_OBSERVED_VALUE_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Enumeration Setting Observed Value writer";
        break;
      case DicesRcDriver::ENUMERATION_SETT_OBSERVED_VALUE_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up Enumeration Setting Observed Value Request reader from QoS file";
        break;
      case DicesRcDriver::ENUMERATION_SETT_OBSERVED_VALUE_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow Enumeration Setting Observed Value Request reader";
        break;
      case DicesRcDriver::ENUMERATION_SETT_OBSERVED_VALUE_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on Enumeration Setting Observed Value Request reader";
        break;
      case DicesRcDriver::ENUMERATION_SETT_OBSERVED_VALUE_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up Enumeration Setting Observed Value Request topic from QoS file";
        break;
      case DicesRcDriver::ENUMERATION_SETT_OBSERVED_VALUE_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow Enumeration Setting Observed Value Request topic";
        break;
      case DicesRcDriver::ENUMERATION_SETT_OBSERVED_VALUE_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set Enumeration Setting Observed Value Request topic content filter";
        break;
      case DicesRcDriver::ENUMERATION_SETT_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Enumeration Setting Observed Value instance";
        break;
      case DicesRcDriver::ENUMERATION_SETT_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Enumeration Setting Observed Value instance to DDS topic";
        break;
      case DicesRcDriver::ENUMERATION_SETT_OBSERVED_VALUE_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Enumeration Setting Observed Value instance from DDS topic";
        break;
      case DicesRcDriver::ENUMERATION_SETT_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Enumeration Setting Observed Value instance";
        break;

      case DicesRcDriver::MDS_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up MDS writer from QoS file";
        break;
      case DicesRcDriver::MDS_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow MDS writer";
        break;
      case DicesRcDriver::MDS_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create MDS instance";
        break;
      case DicesRcDriver::MDS_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write MDS instance to DDS topic";
        break;
      case DicesRcDriver::MDS_INSTANCE_READ_FAILURE:
        code_message = "Failed to read MDS instance from DDS topic";
        break;
      case DicesRcDriver::MDS_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete MDS instance";
        break;

      case DicesRcDriver::VMD_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up VMD writer from QoS file";
        break;
      case DicesRcDriver::VMD_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow VMD writer";
        break;
      case DicesRcDriver::VMD_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create VMD instance";
        break;
      case DicesRcDriver::VMD_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write VMD instance to DDS topic";
        break;
      case DicesRcDriver::VMD_INSTANCE_READ_FAILURE:
        code_message = "Failed to read VMD instance from DDS topic";
        break;
      case DicesRcDriver::VMD_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete VMD instance";
        break;

      case DicesRcDriver::NUMERIC_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Numeric Context instance";
        break;
      case DicesRcDriver::NUMERIC_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to delete Numeric Observed Value instance";
        break;

      case DicesRcDriver::NUMERIC_MEAS_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Numeric Measured Context writer from QoS file";
        break;
      case DicesRcDriver::NUMERIC_MEAS_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Numeric Measured Context writer";
        break;
      case DicesRcDriver::NUMERIC_MEAS_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up Numeric Measured Context Request reader from QoS file";
        break;
      case DicesRcDriver::NUMERIC_MEAS_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow Numeric Measured Context Request reader";
        break;
      case DicesRcDriver::NUMERIC_MEAS_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on Numeric Measured Context Request reader";
        break;
      case DicesRcDriver::NUMERIC_MEAS_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up Numeric Measured Context Request topic from QoS file";
        break;
      case DicesRcDriver::NUMERIC_MEAS_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow Numeric Measured Context Request topic";
        break;
      case DicesRcDriver::NUMERIC_MEAS_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set Numeric Measured Context Request topic content filter";
        break;
      case DicesRcDriver::NUMERIC_MEAS_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Numeric Measured Context instance";
        break;
      case DicesRcDriver::NUMERIC_MEAS_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Numeric Measured Context instance to DDS topic";
        break;
      case DicesRcDriver::NUMERIC_MEAS_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Numeric Measured Context instance from DDS topic";
        break;
      case DicesRcDriver::NUMERIC_MEAS_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Numeric Measured Context instance";
        break;

      case DicesRcDriver::NUMERIC_MEAS_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Numeric Measured Observed Value writer from QoS file";
        break;
      case DicesRcDriver::NUMERIC_MEAS_OBSERVED_VALUE_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Numeric Measured Observed Value writer";
        break;
      case DicesRcDriver::NUMERIC_MEAS_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Numeric Measured Observed Value instance";
        break;
      case DicesRcDriver::NUMERIC_MEAS_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Numeric Measured Observed Value instance to DDS topic";
        break;
      case DicesRcDriver::NUMERIC_MEAS_OBSERVED_VALUE_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Numeric Measured Observed Value instance from DDS topic";
        break;
      case DicesRcDriver::NUMERIC_MEAS_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Numeric Measured Observed Value instance";
        break;

      case DicesRcDriver::NUMERIC_CALC_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Numeric Calculated Context writer from QoS file";
        break;
      case DicesRcDriver::NUMERIC_CALC_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Numeric Calculated Context writer";
        break;
      case DicesRcDriver::NUMERIC_CALC_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up Numeric Calculated Context Request reader from QoS file";
        break;
      case DicesRcDriver::NUMERIC_CALC_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow Numeric Calculated Context Request reader";
        break;
      case DicesRcDriver::NUMERIC_CALC_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on Numeric Calculated Context Request reader";
        break;
      case DicesRcDriver::NUMERIC_CALC_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up Numeric Calculated Context Request topic from QoS file";
        break;
      case DicesRcDriver::NUMERIC_CALC_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow Numeric Calculated Context Request topic";
        break;
      case DicesRcDriver::NUMERIC_CALC_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set Numeric Calculated Context Request topic content filter";
        break;
      case DicesRcDriver::NUMERIC_CALC_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Numeric Calculated Context instance";
        break;
      case DicesRcDriver::NUMERIC_CALC_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Numeric Calculated Context instance to DDS topic";
        break;
      case DicesRcDriver::NUMERIC_CALC_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Numeric Calculated Context instance from DDS topic";
        break;
      case DicesRcDriver::NUMERIC_CALC_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Numeric Calculated Context instance";
        break;

      case DicesRcDriver::NUMERIC_CALC_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Numeric Calculated Observed Value writer from QoS file";
        break;
      case DicesRcDriver::NUMERIC_CALC_OBSERVED_VALUE_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Numeric Calculated Observed Value writer";
        break;
      case DicesRcDriver::NUMERIC_CALC_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Numeric Calculated Observed Value instance";
        break;
      case DicesRcDriver::NUMERIC_CALC_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Numeric Calculated Observed Value instance to DDS topic";
        break;
      case DicesRcDriver::NUMERIC_CALC_OBSERVED_VALUE_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Numeric Calculated Observed Value instance from DDS topic";
        break;
      case DicesRcDriver::NUMERIC_CALC_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Numeric Calculated Observed Value instance";
        break;

      case DicesRcDriver::NUMERIC_SETT_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Numeric Setting Context writer from QoS file";
        break;
      case DicesRcDriver::NUMERIC_SETT_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Numeric Setting Context writer";
        break;
      case DicesRcDriver::NUMERIC_SETT_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up Numeric Setting Context Request reader from QoS file";
        break;
      case DicesRcDriver::NUMERIC_SETT_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow Numeric Setting Context Request reader";
        break;
      case DicesRcDriver::NUMERIC_SETT_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on Numeric Setting Context Request reader";
        break;
      case DicesRcDriver::NUMERIC_SETT_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up Numeric Setting Context Request topic from QoS file";
        break;
      case DicesRcDriver::NUMERIC_SETT_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow Numeric Setting Context Request topic";
        break;
      case DicesRcDriver::NUMERIC_SETT_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set Numeric Setting Context Request topic content filter";
        break;
      case DicesRcDriver::NUMERIC_SETT_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Numeric Setting Context instance";
        break;
      case DicesRcDriver::NUMERIC_SETT_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Numeric Setting Context instance to DDS topic";
        break;
      case DicesRcDriver::NUMERIC_SETT_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Numeric Setting Context instance from DDS topic";
        break;
      case DicesRcDriver::NUMERIC_SETT_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Numeric Setting Context instance";
        break;

      case DicesRcDriver::NUMERIC_SETT_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Numeric Setting Observed Value writer from QoS file";
        break;
      case DicesRcDriver::NUMERIC_SETT_OBSERVED_VALUE_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Numeric Setting Observed Value writer";
        break;
      case DicesRcDriver::NUMERIC_SETT_OBSERVED_VALUE_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up Numeric Setting Observed Value Request reader from QoS file";
        break;
      case DicesRcDriver::NUMERIC_SETT_OBSERVED_VALUE_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow Numeric Setting Observed Value Request reader";
        break;
      case DicesRcDriver::NUMERIC_SETT_OBSERVED_VALUE_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on Numeric Setting Observed Value Request reader";
        break;
      case DicesRcDriver::NUMERIC_SETT_OBSERVED_VALUE_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up Numeric Setting Observed Value Request topic from QoS file";
        break;
      case DicesRcDriver::NUMERIC_SETT_OBSERVED_VALUE_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow Numeric Setting Observed Value Request topic";
        break;
      case DicesRcDriver::NUMERIC_SETT_OBSERVED_VALUE_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set Numeric Setting Observed Value Request topic content filter";
        break;
      case DicesRcDriver::NUMERIC_SETT_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Numeric Setting Observed Value instance";
        break;
      case DicesRcDriver::NUMERIC_SETT_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Numeric Setting Observed Value instance to DDS topic";
        break;
      case DicesRcDriver::NUMERIC_SETT_OBSERVED_VALUE_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Numeric Setting Observed Value instance from DDS topic";
        break;
      case DicesRcDriver::NUMERIC_SETT_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Numeric Setting Observed Value instance";
        break;

      case DicesRcDriver::RTSA_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create RTSA Context instance";
        break;
      case DicesRcDriver::RTSA_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create RTSA Observed Value instance";
        break;

      case DicesRcDriver::RTSA_MEAS_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up RTSA Measured Context writer from QoS file";
        break;
      case DicesRcDriver::RTSA_MEAS_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow RTSA Measured Context writer";
        break;
      case DicesRcDriver::RTSA_MEAS_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up RTSA Measured Context Request reader from QoS file";
        break;
      case DicesRcDriver::RTSA_MEAS_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow RTSA Measured Context Request reader";
        break;
      case DicesRcDriver::RTSA_MEAS_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on RTSA Measured Context Request reader";
        break;
      case DicesRcDriver::RTSA_MEAS_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up RTSA Measured Context Request topic from QoS file";
        break;
      case DicesRcDriver::RTSA_MEAS_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow RTSA Measured Context Request topic";
        break;
      case DicesRcDriver::RTSA_MEAS_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set RTSA Measured Context Request topic content filter";
        break;
      case DicesRcDriver::RTSA_MEAS_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create RTSA Measured Context instance";
        break;
      case DicesRcDriver::RTSA_MEAS_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write RTSA Measured Context instance to DDS topic";
        break;
      case DicesRcDriver::RTSA_MEAS_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read RTSA Measured Context instance from DDS topic";
        break;
      case DicesRcDriver::RTSA_MEAS_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete RTSA Measured Context instance";
        break;

      case DicesRcDriver::RTSA_MEAS_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up RTSA Measured Observed Value writer from QoS file";
        break;
      case DicesRcDriver::RTSA_MEAS_OBSERVED_VALUE_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow RTSA Measured Observed Value writer";
        break;
      case DicesRcDriver::RTSA_MEAS_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create RTSA Measured Observed Value instance";
        break;
      case DicesRcDriver::RTSA_MEAS_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write RTSA Measured Observed Value instance to DDS topic";
        break;
      case DicesRcDriver::RTSA_MEAS_OBSERVED_VALUE_INSTANCE_READ_FAILURE:
        code_message = "Failed to read RTSA Measured Observed Value instance from DDS topic";
        break;
      case DicesRcDriver::RTSA_MEAS_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete RTSA Measured Observed Value instance";
        break;

      case DicesRcDriver::RTSA_CALC_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up RTSA Calculated Context writer from QoS file";
        break;
      case DicesRcDriver::RTSA_CALC_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow RTSA Calculated Context writer";
        break;
      case DicesRcDriver::RTSA_CALC_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up RTSA Calculated Context Request reader from QoS file";
        break;
      case DicesRcDriver::RTSA_CALC_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow RTSA Calculated Context Request reader";
        break;
      case DicesRcDriver::RTSA_CALC_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on RTSA Calculated Context Request reader";
        break;
      case DicesRcDriver::RTSA_CALC_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up RTSA Calculated Context Request topic from QoS file";
        break;
      case DicesRcDriver::RTSA_CALC_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow RTSA Calculated Context Request topic";
        break;
      case DicesRcDriver::RTSA_CALC_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set RTSA Calculated Context Request topic content filter";
        break;
      case DicesRcDriver::RTSA_CALC_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create RTSA Calculated Context instance";
        break;
      case DicesRcDriver::RTSA_CALC_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write RTSA Calculated Context instance to DDS topic";
        break;
      case DicesRcDriver::RTSA_CALC_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read RTSA Calculated Context instance from DDS topic";
        break;
      case DicesRcDriver::RTSA_CALC_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete RTSA Calculated Context instance";
        break;

      case DicesRcDriver::RTSA_CALC_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up RTSA Calculated Observed Value writer from QoS file";
        break;
      case DicesRcDriver::RTSA_CALC_OBSERVED_VALUE_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow RTSA Calculated Observed Value writer";
        break;
      case DicesRcDriver::RTSA_CALC_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create RTSA Calculated Observed Value instance";
        break;
      case DicesRcDriver::RTSA_CALC_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write RTSA Calculated Observed Value instance to DDS topic";
        break;
      case DicesRcDriver::RTSA_CALC_OBSERVED_VALUE_INSTANCE_READ_FAILURE:
        code_message = "Failed to read RTSA Calculated Observed Value instance from DDS topic";
        break;
      case DicesRcDriver::RTSA_CALC_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete RTSA Calculated Observed Value instance";
        break;

      case DicesRcDriver::RTSA_SETT_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up RTSA Setting Context writer from QoS file";
        break;
      case DicesRcDriver::RTSA_SETT_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow RTSA Setting Context writer";
        break;
      case DicesRcDriver::RTSA_SETT_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up RTSA Setting Context Request reader from QoS file";
        break;
      case DicesRcDriver::RTSA_SETT_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow RTSA Setting Context Request reader";
        break;
      case DicesRcDriver::RTSA_SETT_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on RTSA Setting Context Request reader";
        break;
      case DicesRcDriver::RTSA_SETT_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up RTSA Setting Context Request topic from QoS file";
        break;
      case DicesRcDriver::RTSA_SETT_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow RTSA Setting Context Request topic";
        break;
      case DicesRcDriver::RTSA_SETT_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set RTSA Setting Context Request topic content filter";
        break;
      case DicesRcDriver::RTSA_SETT_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create RTSA Setting Context instance";
        break;
      case DicesRcDriver::RTSA_SETT_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write RTSA Setting Context instance to DDS topic";
        break;
      case DicesRcDriver::RTSA_SETT_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read RTSA Setting Context instance from DDS topic";
        break;
      case DicesRcDriver::RTSA_SETT_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete RTSA Setting Context instance";
        break;

      case DicesRcDriver::RTSA_SETT_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up RTSA Setting Observed Value writer from QoS file";
        break;
      case DicesRcDriver::RTSA_SETT_OBSERVED_VALUE_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow RTSA Setting Observed Value writer";
        break;
      case DicesRcDriver::RTSA_SETT_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create RTSA Setting Observed Value instance";
        break;
      case DicesRcDriver::RTSA_SETT_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write RTSA Setting Observed Value instance to DDS topic";
        break;
      case DicesRcDriver::RTSA_SETT_OBSERVED_VALUE_INSTANCE_READ_FAILURE:
        code_message = "Failed to read RTSA Setting Observed Value instance from DDS topic";
        break;
      case DicesRcDriver::RTSA_SETT_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete RTSA Setting Observed Value instance";
        break;

      case DicesRcDriver::TSA_MEAS_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up TSA Measured Context writer from QoS file";
        break;
      case DicesRcDriver::TSA_MEAS_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow TSA Measured Context writer";
        break;
      case DicesRcDriver::TSA_MEAS_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up TSA Measured Context Request reader from QoS file";
        break;
      case DicesRcDriver::TSA_MEAS_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow TSA Measured Context Request reader";
        break;
      case DicesRcDriver::TSA_MEAS_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on TSA Measured Context Request reader";
        break;
      case DicesRcDriver::TSA_MEAS_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up TSA Measured Context Request topic from QoS file";
        break;
      case DicesRcDriver::TSA_MEAS_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow TSA Measured Context Request topic";
        break;
      case DicesRcDriver::TSA_MEAS_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set TSA Measured Context Request topic content filter";
        break;
      case DicesRcDriver::TSA_MEAS_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create TSA Measured Context instance";
        break;
      case DicesRcDriver::TSA_MEAS_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write TSA Measured Context instance to DDS topic";
        break;
      case DicesRcDriver::TSA_MEAS_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read TSA Measured Context instance from DDS topic";
        break;
      case DicesRcDriver::TSA_MEAS_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete TSA Measured Context instance";
        break;

      case DicesRcDriver::TSA_MEAS_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up TSA Measured Observed Value writer from QoS file";
        break;
      case DicesRcDriver::TSA_MEAS_OBSERVED_VALUE_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow TSA Measured Observed Value writer";
        break;
      case DicesRcDriver::TSA_MEAS_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create TSA Measured Observed Value instance";
        break;
      case DicesRcDriver::TSA_MEAS_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write TSA Measured Observed Value instance to DDS topic";
        break;
      case DicesRcDriver::TSA_MEAS_OBSERVED_VALUE_INSTANCE_READ_FAILURE:
        code_message = "Failed to read TSA Measured Observed Value instance from DDS topic";
        break;
      case DicesRcDriver::TSA_MEAS_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete TSA Measured Observed Value instance";
        break;

      case DicesRcDriver::TSA_CALC_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up TSA Calculated Context writer from QoS file";
        break;
      case DicesRcDriver::TSA_CALC_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow TSA Calculated Context writer";
        break;
      case DicesRcDriver::TSA_CALC_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up TSA Calculated Context Request reader from QoS file";
        break;
      case DicesRcDriver::TSA_CALC_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow TSA Calculated Context Request reader";
        break;
      case DicesRcDriver::TSA_CALC_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on TSA Calculated Context Request reader";
        break;
      case DicesRcDriver::TSA_CALC_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up TSA Calculated Context Request topic from QoS file";
        break;
      case DicesRcDriver::TSA_CALC_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow TSA Calculated Context Request topic";
        break;
      case DicesRcDriver::TSA_CALC_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set TSA Calculated Context Request topic content filter";
        break;
      case DicesRcDriver::TSA_CALC_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create TSA Calculated Context instance";
        break;
      case DicesRcDriver::TSA_CALC_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write TSA Calculated Context instance to DDS topic";
        break;
      case DicesRcDriver::TSA_CALC_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read TSA Calculated Context instance from DDS topic";
        break;
      case DicesRcDriver::TSA_CALC_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete TSA Calculated Context instance";
        break;

      case DicesRcDriver::TSA_CALC_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up TSA Calculated Observed Value writer from QoS file";
        break;
      case DicesRcDriver::TSA_CALC_OBSERVED_VALUE_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow TSA Calculated Observed Value writer";
        break;
      case DicesRcDriver::TSA_CALC_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create TSA Calculated Observed Value instance";
        break;
      case DicesRcDriver::TSA_CALC_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write TSA Calculated Observed Value instance to DDS topic";
        break;
      case DicesRcDriver::TSA_CALC_OBSERVED_VALUE_INSTANCE_READ_FAILURE:
        code_message = "Failed to read TSA Calculated Observed Value instance from DDS topic";
        break;
      case DicesRcDriver::TSA_CALC_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete TSA Calculated Observed Value instance";
        break;

      case DicesRcDriver::TSA_SETT_CONTEXT_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up TSA Setting Context writer from QoS file";
        break;
      case DicesRcDriver::TSA_SETT_CONTEXT_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow TSA Setting Context writer";
        break;
      case DicesRcDriver::TSA_SETT_CONTEXT_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up TSA Setting Context Request reader from QoS file";
        break;
      case DicesRcDriver::TSA_SETT_CONTEXT_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow TSA Setting Context Request reader";
        break;
      case DicesRcDriver::TSA_SETT_CONTEXT_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on TSA Setting Context Request reader";
        break;
      case DicesRcDriver::TSA_SETT_CONTEXT_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up TSA Setting Context Request topic from QoS file";
        break;
      case DicesRcDriver::TSA_SETT_CONTEXT_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow TSA Setting Context Request topic";
        break;
      case DicesRcDriver::TSA_SETT_CONTEXT_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set TSA Setting Context Request topic content filter";
        break;
      case DicesRcDriver::TSA_SETT_CONTEXT_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create TSA Setting Context instance";
        break;
      case DicesRcDriver::TSA_SETT_CONTEXT_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write TSA Setting Context instance to DDS topic";
        break;
      case DicesRcDriver::TSA_SETT_CONTEXT_INSTANCE_READ_FAILURE:
        code_message = "Failed to read TSA Setting Context instance from DDS topic";
        break;
      case DicesRcDriver::TSA_SETT_CONTEXT_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete TSA Setting Context instance";
        break;

      case DicesRcDriver::TSA_SETT_OBSERVED_VALUE_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up TSA Setting Observed Value writer from QoS file";
        break;
      case DicesRcDriver::TSA_SETT_OBSERVED_VALUE_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow TSA Setting Observed Value writer";
        break;
      case DicesRcDriver::TSA_SETT_OBSERVED_VALUE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create TSA Setting Observed Value instance";
        break;
      case DicesRcDriver::TSA_SETT_OBSERVED_VALUE_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write TSA Setting Observed Value instance to DDS topic";
        break;
      case DicesRcDriver::TSA_SETT_OBSERVED_VALUE_INSTANCE_READ_FAILURE:
        code_message = "Failed to read TSA Setting Observed Value instance from DDS topic";
        break;
      case DicesRcDriver::TSA_SETT_OBSERVED_VALUE_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete TSA Setting Observed Value instance";
        break;

      case DicesRcDriver::ALLERGY_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Allergy writer from QoS file";
        break;
      case DicesRcDriver::ALLERGY_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Allergy writer";
        break;
      case DicesRcDriver::ALLERGY_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Allergy instance";
        break;
      case DicesRcDriver::ALLERGY_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Allergy instance to DDS topic";
        break;
      case DicesRcDriver::ALLERGY_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Allergy instance from DDS topic";
        break;
      case DicesRcDriver::ALLERGY_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Allergy instance";
        break;
        
      case DicesRcDriver::DIAGNOSIS_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up Diagnosis writer from QoS file";
        break;
      case DicesRcDriver::DIAGNOSIS_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow Diagnosis writer";
        break;
      case DicesRcDriver::DIAGNOSIS_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Diagnosis instance";
        break;
      case DicesRcDriver::DIAGNOSIS_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Diagnosis instance to DDS topic";
        break;
      case DicesRcDriver::DIAGNOSIS_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Diagnosis instance from DDS topic";
        break;
      case DicesRcDriver::DIAGNOSIS_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Diagnosis instance";
        break;

      case DicesRcDriver::DXHISTORY_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up DxHistory writer from QoS file";
        break;
      case DicesRcDriver::DXHISTORY_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow DxHistory writer";
        break;
      case DicesRcDriver::DXHISTORY_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create DxHistory instance";
        break;
      case DicesRcDriver::DXHISTORY_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write DxHistory instance to DDS topic";
        break;
      case DicesRcDriver::DXHISTORY_INSTANCE_READ_FAILURE:
        code_message = "Failed to read DxHistory instance from DDS topic";
        break;
      case DicesRcDriver::DXHISTORY_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete DxHistory instance";
        break;

      case DicesRcDriver::PATIENT_MEDICATION_WRITER_LOOKUP_FAILURE:
        code_message = "Failed to look up PatientMedication writer from QoS file";
        break;
      case DicesRcDriver::PATIENT_MEDICATION_WRITER_NARROW_FAILURE:
        code_message = "Failed to narrow PatientMedication writer";
        break;
      case DicesRcDriver::PATIENT_MEDICATION_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create PatientMedication instance";
        break;
      case DicesRcDriver::PATIENT_MEDICATION_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write PatientMedication instance to DDS topic";
        break;
      case DicesRcDriver::PATIENT_MEDICATION_INSTANCE_READ_FAILURE:
        code_message = "Failed to read PatientMedication instance from DDS topic";
        break;
      case DicesRcDriver::PATIENT_MEDICATION_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete PatientMedication instance";
        break;

      case DicesRcDriver::DEVICE_DRIVER_STATE_REQUEST_READER_LOOKUP_FAILURE:
        code_message = "Failed to look up Device Driver State Request reader from QoS file";
        break;
      case DicesRcDriver::DEVICE_DRIVER_STATE_REQUEST_READER_NARROW_FAILURE:
        code_message = "Failed to narrow Device Driver State Request reader";
        break;
      case DicesRcDriver::DEVICE_DRIVER_STATE_REQUEST_READER_LOAN_RETURN_FAILURE:
        code_message = "Failed to return loan on Device Driver State Request reader";
        break;
      case DicesRcDriver::DEVICE_DRIVER_STATE_REQUEST_TOPIC_LOOKUP_FAILURE:
        code_message = "Failed to look up Device Driver State Request topic from QoS file";
        break;
      case DicesRcDriver::DEVICE_DRIVER_STATE_REQUEST_TOPIC_NARROW_FAILURE:
        code_message = "Failed to narrow Device Driver State Request topic";
        break;
      case DicesRcDriver::DEVICE_DRIVER_STATE_REQUEST_TOPIC_FILTER_FAILURE:
        code_message = "Failed to set Device Driver State Request topic content filter";
        break;
      case DicesRcDriver::DEVICE_DRIVER_STATE_INSTANCE_CREATE_FAILURE:
        code_message = "Failed to create Device Driver State instance";
        break;
      case DicesRcDriver::DEVICE_DRIVER_STATE_INSTANCE_WRITE_FAILURE:
        code_message = "Failed to write Device Driver State instance to DDS topic";
        break;
      case DicesRcDriver::DEVICE_DRIVER_STATE_INSTANCE_READ_FAILURE:
        code_message = "Failed to read Device Driver State instance from DDS topic";
        break;
      case DicesRcDriver::DEVICE_DRIVER_STATE_INSTANCE_DELETE_FAILURE:
        code_message = "Failed to delete Device Driver State instance";
        break;

      case DicesRcDriver::SET_ICE_ID_FAILURE:
        code_message = "Failed to set ICE ID in Parser";
        break;

      case DicesRcDriver::DRIVER_STATUS_HANDLER_INIT_FAILURE:
        code_message = "Failed to initialize Device Driver Status handler";
        break;
      case DicesRcDriver::DRIVER_STATUS_CONNECTING_FAILURE:
        code_message = "Failed to set Driver Status to Connecting";
        break;
      case DicesRcDriver::DRIVER_STATUS_OPERATING_FAILURE:
        code_message = "Failed to set Driver Status to Operating";
        break;
      case DicesRcDriver::DRIVER_STATUS_SHUTDOWN_FAILURE:
        code_message = "Failed to set Driver Status to Shutdown";
        break;
      case DicesRcDriver::DRIVER_STATUS_ERROR_FAILURE:
        code_message = "Failed to set Driver Status to Error";
        break;
      case DicesRcDriver::DRIVER_STATUS_HANDLER_SHUTDOWN_FAILURE:
        code_message = "Failed to shutdown Device Driver Status handler";
        break;

      case DicesRcDriver::DELETE_CONTAINED_ENTITIES_FAILURE:
        code_message = "Failed to delete DDS entities from participant";
        break;
      case DicesRcDriver::DELETE_PARTICIPANT_FAILURE:
        code_message = "Failed to delete DDS Domain participant";
        break;
      case DicesRcDriver::FINALIZE_INSTANCE_FAILURE:
        code_message = "Failed to finalize instance with the participant factory";
        break;

      case DicesRcDriver::NO_NEW_DATA:
        code_message = "No new data on instance since it was last published";
        break;

      case DicesRcDriver::HANDSHAKE_DONE:
        code_message = "Driver has finished handshaking with device";
        break;
      case DicesRcDriver::QUIT:
        code_message = "Driver has been asked to quit";
        break;

      case DicesRcDriver::MEMORY_ALLOCATION_FAILURE:
        code_message = "Failure allocating memory";
        break;

      case DicesRcDriver::UNDEFINED_ENUM_VALUE_FAILURE:
        code_message = "Value of enum class variable not in enum class definition";
        break;
      case DicesRcDriver::PARAMETER_RANGE_FAILURE:
        code_message = "Method parameter not valid for method";
        break;

      case DicesRcDriver::GET_RELATIVE_TIME_FAILURE:
        code_message = "Failure to get relative time";
        break;
      case DicesRcDriver::GET_TIME_OF_DAY_UTC_FAILURE:
        code_message = "Failure to get time of day UTC";
        break;

      case DicesRcDriver::BASE_COMM_OPEN_FAILURE:
        code_message = "Base communication open failed";
        break;
      case DicesRcDriver::BASE_COMM_CLOSE_FAILURE:
        code_message = "Base communication close failed";
        break;
      case DicesRcDriver::BASE_COMM_SEND_FAILURE:
        code_message = "Base communication send failed";
        break;
      case DicesRcDriver::BASE_COMM_READ_FAILURE:
        code_message = "Base communication read failed";
        break;
      case DicesRcDriver::BASE_COMM_FLUSH_FAILURE:
        code_message = "Base communication flush failed";
        break;

      case DicesRcDriver::BASE_COMM_POINTER_IS_NULL:
        code_message = "Base communication pointer is null";
        break;
      case DicesRcDriver::PARSER_POINTER_IS_NULL:
        code_message = "Parser pointer is null";
        break;
      case DicesRcDriver::COMMAND_BUFFER_POINTER_IS_NULL:
        code_message = "Command buffer pointer is null";
        break;
      case DicesRcDriver::RESPONSE_BUFFER_POINTER_IS_NULL:
        code_message = "Response buffer pointer is null";
        break;
      case DicesRcDriver::READ_TIMEOUT:
        code_message = "Read timeout";
        break;
      case DicesRcDriver::DEVICE_DISCONNECTION:
        code_message = "Detected device disconnection";
        break;

      case DicesRcDriver::ERROR_PARSING_JSON_RESPONSE:
        code_message = "Unable to parse json database result";
        break;

      case DicesRcDriver::ALLERGY_READER_LOOKUP_FAILURE:
        code_message = "Failed to lookup Allergy Reader";
        break;

      case DicesRcDriver::ALLERGY_READER_RETURN_LOAN_FAILURE:
        code_message = "Failed to return_loan for Allergy Reader";
        break;

      case DicesRcDriver::ALLERGY_READER_NARROW_FAILURE:
        code_message = "Failed narrow Allergy Reader";
        break;

      case DicesRcDriver::PARSE_RESPONSE_FAILURE:
        code_message = "Failed to parse response from device";
        break;

      default: // should not be reached
        code_message = "Unknown Status Code: ";
        code_message.append(std::to_string(static_cast<int>(error_code)));
        break;
    }
    return code_message;
  }
 private:
  // Disallow use of implicitly generated member functions:
  DicesRcDriverStatusMessage(const DicesRcDriverStatusMessage &src);
  DicesRcDriverStatusMessage &operator=(const DicesRcDriverStatusMessage &rhs);
};

#endif	// DICES_RC_DRIVER_H_

