/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: model/medsys3.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "medsys3.pb-c.h"
void   medsys3__ident__init
                     (Medsys3__Ident         *message)
{
  static const Medsys3__Ident init_value = MEDSYS3__IDENT__INIT;
  *message = init_value;
}
size_t medsys3__ident__get_packed_size
                     (const Medsys3__Ident *message)
{
  assert(message->base.descriptor == &medsys3__ident__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t medsys3__ident__pack
                     (const Medsys3__Ident *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &medsys3__ident__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t medsys3__ident__pack_to_buffer
                     (const Medsys3__Ident *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &medsys3__ident__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Medsys3__Ident *
       medsys3__ident__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Medsys3__Ident *)
     protobuf_c_message_unpack (&medsys3__ident__descriptor,
                                allocator, len, data);
}
void   medsys3__ident__free_unpacked
                     (Medsys3__Ident *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &medsys3__ident__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   medsys3__status__init
                     (Medsys3__Status         *message)
{
  static const Medsys3__Status init_value = MEDSYS3__STATUS__INIT;
  *message = init_value;
}
size_t medsys3__status__get_packed_size
                     (const Medsys3__Status *message)
{
  assert(message->base.descriptor == &medsys3__status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t medsys3__status__pack
                     (const Medsys3__Status *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &medsys3__status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t medsys3__status__pack_to_buffer
                     (const Medsys3__Status *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &medsys3__status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Medsys3__Status *
       medsys3__status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Medsys3__Status *)
     protobuf_c_message_unpack (&medsys3__status__descriptor,
                                allocator, len, data);
}
void   medsys3__status__free_unpacked
                     (Medsys3__Status *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &medsys3__status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   medsys3__measurement__init
                     (Medsys3__Measurement         *message)
{
  static const Medsys3__Measurement init_value = MEDSYS3__MEASUREMENT__INIT;
  *message = init_value;
}
size_t medsys3__measurement__get_packed_size
                     (const Medsys3__Measurement *message)
{
  assert(message->base.descriptor == &medsys3__measurement__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t medsys3__measurement__pack
                     (const Medsys3__Measurement *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &medsys3__measurement__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t medsys3__measurement__pack_to_buffer
                     (const Medsys3__Measurement *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &medsys3__measurement__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Medsys3__Measurement *
       medsys3__measurement__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Medsys3__Measurement *)
     protobuf_c_message_unpack (&medsys3__measurement__descriptor,
                                allocator, len, data);
}
void   medsys3__measurement__free_unpacked
                     (Medsys3__Measurement *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &medsys3__measurement__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   medsys3__sigevent__init
                     (Medsys3__Sigevent         *message)
{
  static const Medsys3__Sigevent init_value = MEDSYS3__SIGEVENT__INIT;
  *message = init_value;
}
size_t medsys3__sigevent__get_packed_size
                     (const Medsys3__Sigevent *message)
{
  assert(message->base.descriptor == &medsys3__sigevent__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t medsys3__sigevent__pack
                     (const Medsys3__Sigevent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &medsys3__sigevent__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t medsys3__sigevent__pack_to_buffer
                     (const Medsys3__Sigevent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &medsys3__sigevent__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Medsys3__Sigevent *
       medsys3__sigevent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Medsys3__Sigevent *)
     protobuf_c_message_unpack (&medsys3__sigevent__descriptor,
                                allocator, len, data);
}
void   medsys3__sigevent__free_unpacked
                     (Medsys3__Sigevent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &medsys3__sigevent__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor medsys3__ident__field_descriptors[5] =
{
  {
    "model",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Ident, model),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_no",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Ident, serial_no),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hospital_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Ident, hospital_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sw_expire",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Ident, sw_expire),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sw_version",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Ident, sw_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned medsys3__ident__field_indices_by_name[] = {
  2,   /* field[2] = hospital_id */
  0,   /* field[0] = model */
  1,   /* field[1] = serial_no */
  3,   /* field[3] = sw_expire */
  4,   /* field[4] = sw_version */
};
static const ProtobufCIntRange medsys3__ident__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor medsys3__ident__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "medsys3.ident",
  "Ident",
  "Medsys3__Ident",
  "medsys3",
  sizeof(Medsys3__Ident),
  5,
  medsys3__ident__field_descriptors,
  medsys3__ident__field_indices_by_name,
  1,  medsys3__ident__number_ranges,
  (ProtobufCMessageInit) medsys3__ident__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor medsys3__status__field_descriptors[3] =
{
  {
    "drug_a",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Status, drug_a),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drug_b",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Status, drug_b),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drug_c",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Status, drug_c),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned medsys3__status__field_indices_by_name[] = {
  0,   /* field[0] = drug_a */
  1,   /* field[1] = drug_b */
  2,   /* field[2] = drug_c */
};
static const ProtobufCIntRange medsys3__status__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor medsys3__status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "medsys3.status",
  "Status",
  "Medsys3__Status",
  "medsys3",
  sizeof(Medsys3__Status),
  3,
  medsys3__status__field_descriptors,
  medsys3__status__field_indices_by_name,
  1,  medsys3__status__number_ranges,
  (ProtobufCMessageInit) medsys3__status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor medsys3__measurement__field_descriptors[16] =
{
  {
    "ins_status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Measurement, ins_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pa_dev_status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Measurement, pa_dev_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pb_dev_status",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Measurement, pb_dev_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pc_dev_status",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Measurement, pc_dev_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pa_inf_status",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Measurement, pa_inf_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pb_inf_status",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Measurement, pb_inf_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pc_inf_status",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Measurement, pc_inf_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pa_rate",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Measurement, pa_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pb_rate",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Measurement, pb_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pc_rate",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Measurement, pc_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pa_infused",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Measurement, pa_infused),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pb_infused",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Measurement, pb_infused),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pc_infused",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Measurement, pc_infused),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pa_sec_infused",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Measurement, pa_sec_infused),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pb_sec_infused",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Measurement, pb_sec_infused),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pc_sec_infused",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Measurement, pc_sec_infused),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned medsys3__measurement__field_indices_by_name[] = {
  0,   /* field[0] = ins_status */
  1,   /* field[1] = pa_dev_status */
  4,   /* field[4] = pa_inf_status */
  10,   /* field[10] = pa_infused */
  7,   /* field[7] = pa_rate */
  13,   /* field[13] = pa_sec_infused */
  2,   /* field[2] = pb_dev_status */
  5,   /* field[5] = pb_inf_status */
  11,   /* field[11] = pb_infused */
  8,   /* field[8] = pb_rate */
  14,   /* field[14] = pb_sec_infused */
  3,   /* field[3] = pc_dev_status */
  6,   /* field[6] = pc_inf_status */
  12,   /* field[12] = pc_infused */
  9,   /* field[9] = pc_rate */
  15,   /* field[15] = pc_sec_infused */
};
static const ProtobufCIntRange medsys3__measurement__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 16 }
};
const ProtobufCMessageDescriptor medsys3__measurement__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "medsys3.measurement",
  "Measurement",
  "Medsys3__Measurement",
  "medsys3",
  sizeof(Medsys3__Measurement),
  16,
  medsys3__measurement__field_descriptors,
  medsys3__measurement__field_indices_by_name,
  1,  medsys3__measurement__number_ranges,
  (ProtobufCMessageInit) medsys3__measurement__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor medsys3__sigevent__field_descriptors[4] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Sigevent, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pump",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Sigevent, pump),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aaf_type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Sigevent, aaf_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aaf_index",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Medsys3__Sigevent, aaf_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned medsys3__sigevent__field_indices_by_name[] = {
  3,   /* field[3] = aaf_index */
  2,   /* field[2] = aaf_type */
  0,   /* field[0] = code */
  1,   /* field[1] = pump */
};
static const ProtobufCIntRange medsys3__sigevent__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor medsys3__sigevent__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "medsys3.sigevent",
  "Sigevent",
  "Medsys3__Sigevent",
  "medsys3",
  sizeof(Medsys3__Sigevent),
  4,
  medsys3__sigevent__field_descriptors,
  medsys3__sigevent__field_indices_by_name,
  1,  medsys3__sigevent__number_ranges,
  (ProtobufCMessageInit) medsys3__sigevent__init,
  NULL,NULL,NULL    /* reserved[123] */
};
