package idea.datamanager.sql;

// Generated Jun 7, 2008 8:07:08 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Colors generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@NamedQueries( {
    @NamedQuery( name = "tranByLocation", query = "from TranLog t where t.deviceLoc=:deviceLoc order by t.tm" )
    , @NamedQuery( name = "tranByPatient", query = "from TranLog t where t.patientOID=:patientOID order by t.tm" )
    } )
@Table(name = "TRAN_LOG", catalog = "idea")
public class TranLog implements java.io.Serializable {

	private long oid;

	private Date tm;

	private String devType;
	private long patientOID;
	private long deviceOID;
	private String deviceLoc;

	public TranLog() {
	}

	public TranLog( Date tm, String devType, long deviceOID, long patientOID, String deviceLoc) {
		this.tm = tm;
		this.devType = devType;
		this.patientOID = patientOID;
		this.deviceOID = deviceOID;
		this.deviceLoc = deviceLoc;
		
		System.out.println( "saving reference to devOid: " + deviceOID );
	}

	@Id
    // @GeneratedValue(strategy=GenerationType.IDENTITY)
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "guid")
	// @Column(name = "OID", unique = true, nullable = false)
	public long getOid() {
		return this.oid;
	}

	public void setOid(long oid) {
		this.oid = oid;
	}

	@Column(name = "TM", unique = false, nullable = false)
	public Date getTm() {
		return this.tm;
	}

	public void setTm(Date tm) {
		this.tm = tm;
	}

	@Column(name = "DEV_TYPE", length = 16, nullable = false)
	public String getDevType() {
		return this.devType;
	}

	public void setDevType(String devType) {
		this.devType = devType;
	}

	@Column(name = "PATIENT_OID",  nullable = false)
	public long getPatientOID() {
		return this.patientOID;
	}

	public void setPatientOID(long patientOID) {
		this.patientOID = patientOID;
	}

	@Column(name = "DEV_OID", nullable = false)
	public long getDeviceOID() {
		return this.deviceOID;
	}

	public void setDeviceOID(long deviceOID) {
		this.deviceOID = deviceOID;
	}

	@Column(name = "DEV_LOC", length=16, nullable = false)
	public String getDeviceLoc() {
		return this.deviceLoc;
	}

	public void setDeviceLoc(String deviceLoc) {
		this.deviceLoc = deviceLoc;
	}

}
