//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.01 at 04:33:03 PM CDT 
//


package idea.mg;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the idea.mg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MgWaveformBlock_QNAME = new QName("http://idea.mil/ws", "mg-waveform-block");
    private final static QName _MgJobReq_QNAME = new QName("http://idea.mil/ws", "mg-jobReq");
    private final static QName _MgDevReply_QNAME = new QName("http://idea.mil/ws", "mg-devReply");
    private final static QName _MgNumericBlock_QNAME = new QName("http://idea.mil/ws", "mg-numeric-block");
    private final static QName _MgCapabilityReq_QNAME = new QName("http://idea.mil/ws", "mg-capabilityReq");
    private final static QName _MgStatusReply_QNAME = new QName("http://idea.mil/ws", "mg-statusReply");
    private final static QName _MgCapabilityReply_QNAME = new QName("http://idea.mil/ws", "mg-capabilityReply");
    private final static QName _MgStatusReq_QNAME = new QName("http://idea.mil/ws", "mg-statusReq");
    private final static QName _MgConfigReply_QNAME = new QName("http://idea.mil/ws", "mg-configReply");
    private final static QName _MgConfigReq_QNAME = new QName("http://idea.mil/ws", "mg-configReq");
    private final static QName _MgDevReq_QNAME = new QName("http://idea.mil/ws", "mg-devReq");
    private final static QName _MgPing_QNAME = new QName("http://idea.mil/ws", "mg-ping");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: idea.mg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MgDevReqType }
     * 
     */
    public MgDevReqType createMgDevReqType() {
        return new MgDevReqType();
    }

    /**
     * Create an instance of {@link MgNumericBlockType }
     * 
     */
    public MgNumericBlockType createMgNumericBlockType() {
        return new MgNumericBlockType();
    }

    /**
     * Create an instance of {@link MgWaveformBlockType }
     * 
     */
    public MgWaveformBlockType createMgWaveformBlockType() {
        return new MgWaveformBlockType();
    }

    /**
     * Create an instance of {@link MgCapabilityReplyType }
     * 
     */
    public MgCapabilityReplyType createMgCapabilityReplyType() {
        return new MgCapabilityReplyType();
    }

    /**
     * Create an instance of {@link MgConfigReqType }
     * 
     */
    public MgConfigReqType createMgConfigReqType() {
        return new MgConfigReqType();
    }

    /**
     * Create an instance of {@link MgCapabilityReqType }
     * 
     */
    public MgCapabilityReqType createMgCapabilityReqType() {
        return new MgCapabilityReqType();
    }

    /**
     * Create an instance of {@link MgConfigReplyType }
     * 
     */
    public MgConfigReplyType createMgConfigReplyType() {
        return new MgConfigReplyType();
    }

    /**
     * Create an instance of {@link MgPingType }
     * 
     */
    public MgPingType createMgPingType() {
        return new MgPingType();
    }

    /**
     * Create an instance of {@link MgStatusReplyType }
     * 
     */
    public MgStatusReplyType createMgStatusReplyType() {
        return new MgStatusReplyType();
    }

    /**
     * Create an instance of {@link MgStatusReqType }
     * 
     */
    public MgStatusReqType createMgStatusReqType() {
        return new MgStatusReqType();
    }

    /**
     * Create an instance of {@link MgNumeric }
     * 
     */
    public MgNumeric createMgNumeric() {
        return new MgNumeric();
    }

    /**
     * Create an instance of {@link MgDevReplyType }
     * 
     */
    public MgDevReplyType createMgDevReplyType() {
        return new MgDevReplyType();
    }

    /**
     * Create an instance of {@link MgWaveformType }
     * 
     */
    public MgWaveformType createMgWaveformType() {
        return new MgWaveformType();
    }

    /**
     * Create an instance of {@link MgJobReqType }
     * 
     */
    public MgJobReqType createMgJobReqType() {
        return new MgJobReqType();
    }

    /**
     * Create an instance of {@link MgDevMeasure }
     * 
     */
    public MgDevMeasure createMgDevMeasure() {
        return new MgDevMeasure();
    }

    /**
     * Create an instance of {@link MgDeviceStatusType }
     * 
     */
    public MgDeviceStatusType createMgDeviceStatusType() {
        return new MgDeviceStatusType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MgWaveformBlockType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://idea.mil/ws", name = "mg-waveform-block")
    public JAXBElement<MgWaveformBlockType> createMgWaveformBlock(MgWaveformBlockType value) {
        return new JAXBElement<MgWaveformBlockType>(_MgWaveformBlock_QNAME, MgWaveformBlockType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MgJobReqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://idea.mil/ws", name = "mg-jobReq")
    public JAXBElement<MgJobReqType> createMgJobReq(MgJobReqType value) {
        return new JAXBElement<MgJobReqType>(_MgJobReq_QNAME, MgJobReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MgDevReplyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://idea.mil/ws", name = "mg-devReply")
    public JAXBElement<MgDevReplyType> createMgDevReply(MgDevReplyType value) {
        return new JAXBElement<MgDevReplyType>(_MgDevReply_QNAME, MgDevReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MgNumericBlockType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://idea.mil/ws", name = "mg-numeric-block")
    public JAXBElement<MgNumericBlockType> createMgNumericBlock(MgNumericBlockType value) {
        return new JAXBElement<MgNumericBlockType>(_MgNumericBlock_QNAME, MgNumericBlockType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MgCapabilityReqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://idea.mil/ws", name = "mg-capabilityReq")
    public JAXBElement<MgCapabilityReqType> createMgCapabilityReq(MgCapabilityReqType value) {
        return new JAXBElement<MgCapabilityReqType>(_MgCapabilityReq_QNAME, MgCapabilityReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MgStatusReplyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://idea.mil/ws", name = "mg-statusReply")
    public JAXBElement<MgStatusReplyType> createMgStatusReply(MgStatusReplyType value) {
        return new JAXBElement<MgStatusReplyType>(_MgStatusReply_QNAME, MgStatusReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MgCapabilityReplyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://idea.mil/ws", name = "mg-capabilityReply")
    public JAXBElement<MgCapabilityReplyType> createMgCapabilityReply(MgCapabilityReplyType value) {
        return new JAXBElement<MgCapabilityReplyType>(_MgCapabilityReply_QNAME, MgCapabilityReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MgStatusReqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://idea.mil/ws", name = "mg-statusReq")
    public JAXBElement<MgStatusReqType> createMgStatusReq(MgStatusReqType value) {
        return new JAXBElement<MgStatusReqType>(_MgStatusReq_QNAME, MgStatusReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MgConfigReplyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://idea.mil/ws", name = "mg-configReply")
    public JAXBElement<MgConfigReplyType> createMgConfigReply(MgConfigReplyType value) {
        return new JAXBElement<MgConfigReplyType>(_MgConfigReply_QNAME, MgConfigReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MgConfigReqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://idea.mil/ws", name = "mg-configReq")
    public JAXBElement<MgConfigReqType> createMgConfigReq(MgConfigReqType value) {
        return new JAXBElement<MgConfigReqType>(_MgConfigReq_QNAME, MgConfigReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MgDevReqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://idea.mil/ws", name = "mg-devReq")
    public JAXBElement<MgDevReqType> createMgDevReq(MgDevReqType value) {
        return new JAXBElement<MgDevReqType>(_MgDevReq_QNAME, MgDevReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MgPingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://idea.mil/ws", name = "mg-ping")
    public JAXBElement<MgPingType> createMgPing(MgPingType value) {
        return new JAXBElement<MgPingType>(_MgPing_QNAME, MgPingType.class, null, value);
    }

}
