/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package idea.jljack;

public class DWAV {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DWAV(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DWAV obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        U3JNI.delete_DWAV(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDdat(SWIGTYPE_p_double value) {
    U3JNI.DWAV_ddat_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getDdat() {
    long cPtr = U3JNI.DWAV_ddat_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public DWAV() {
    this(U3JNI.new_DWAV(), true);
  }

}
