/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package idea.jljack;

public class IWAV {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IWAV(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IWAV obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        U3JNI.delete_IWAV(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIdat(SWIGTYPE_p_int value) {
    U3JNI.IWAV_idat_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getIdat() {
    long cPtr = U3JNI.IWAV_idat_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public IWAV() {
    this(U3JNI.new_IWAV(), true);
  }

}
