/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package idea.jljack;

public class SWIGTYPE_p_U3DataModel {
  private long swigCPtr;

  protected SWIGTYPE_p_U3DataModel(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_U3DataModel() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_U3DataModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

