/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package idea.jljack;

public class U3_TDAC_CALIBRATION_INFORMATION {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected U3_TDAC_CALIBRATION_INFORMATION(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(U3_TDAC_CALIBRATION_INFORMATION obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        U3JNI.delete_U3_TDAC_CALIBRATION_INFORMATION(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProdID(short value) {
    U3JNI.U3_TDAC_CALIBRATION_INFORMATION_prodID_set(swigCPtr, this, value);
  }

  public short getProdID() {
    return U3JNI.U3_TDAC_CALIBRATION_INFORMATION_prodID_get(swigCPtr, this);
  }

  public void setCcConstants(double[] value) {
    U3JNI.U3_TDAC_CALIBRATION_INFORMATION_ccConstants_set(swigCPtr, this, value);
  }

  public double[] getCcConstants() {
    return U3JNI.U3_TDAC_CALIBRATION_INFORMATION_ccConstants_get(swigCPtr, this);
  }

  public U3_TDAC_CALIBRATION_INFORMATION() {
    this(U3JNI.new_U3_TDAC_CALIBRATION_INFORMATION(), true);
  }

}
