/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package idea.jljack;

public interface U3Constants {
  public final static int LJ_tc2MHZ = U3JNI.LJ_tc2MHZ_get();
  public final static int LJ_tc6MHZ = U3JNI.LJ_tc6MHZ_get();
  public final static int LJ_tc24MHZ = U3JNI.LJ_tc24MHZ_get();
  public final static int LJ_tc500KHZ_DIV = U3JNI.LJ_tc500KHZ_DIV_get();
  public final static int LJ_tc2MHZ_DIV = U3JNI.LJ_tc2MHZ_DIV_get();
  public final static int LJ_tc6MHZ_DIV = U3JNI.LJ_tc6MHZ_DIV_get();
  public final static int LJ_tc24MHZ_DIV = U3JNI.LJ_tc24MHZ_DIV_get();
  public final static int LJ_tc4MHZ = U3JNI.LJ_tc4MHZ_get();
  public final static int LJ_tc12MHZ = U3JNI.LJ_tc12MHZ_get();
  public final static int LJ_tc48MHZ = U3JNI.LJ_tc48MHZ_get();
  public final static int LJ_tc1MHZ_DIV = U3JNI.LJ_tc1MHZ_DIV_get();
  public final static int LJ_tc4MHZ_DIV = U3JNI.LJ_tc4MHZ_DIV_get();
  public final static int LJ_tc12MHZ_DIV = U3JNI.LJ_tc12MHZ_DIV_get();
  public final static int LJ_tc48MHZ_DIV = U3JNI.LJ_tc48MHZ_DIV_get();
  public final static int LJ_tmPWM16 = U3JNI.LJ_tmPWM16_get();
  public final static int LJ_tmPWM8 = U3JNI.LJ_tmPWM8_get();
  public final static int LJ_tmRISINGEDGES32 = U3JNI.LJ_tmRISINGEDGES32_get();
  public final static int LJ_tmFALLINGEDGES32 = U3JNI.LJ_tmFALLINGEDGES32_get();
  public final static int LJ_tmDUTYCYCLE = U3JNI.LJ_tmDUTYCYCLE_get();
  public final static int LJ_tmFIRMCOUNTER = U3JNI.LJ_tmFIRMCOUNTER_get();
  public final static int LJ_tmFIRMCOUNTERDEBOUNCE = U3JNI.LJ_tmFIRMCOUNTERDEBOUNCE_get();
  public final static int LJ_tmFREQOUT = U3JNI.LJ_tmFREQOUT_get();
  public final static int LJ_tmQUAD = U3JNI.LJ_tmQUAD_get();
  public final static int LJ_tmTIMERSTOP = U3JNI.LJ_tmTIMERSTOP_get();
  public final static int LJ_tmSYSTIMERLOW = U3JNI.LJ_tmSYSTIMERLOW_get();
  public final static int LJ_tmSYSTIMERHIGH = U3JNI.LJ_tmSYSTIMERHIGH_get();
  public final static int LJ_tmRISINGEDGES16 = U3JNI.LJ_tmRISINGEDGES16_get();
  public final static int LJ_tmFALLINGEDGES16 = U3JNI.LJ_tmFALLINGEDGES16_get();
}
