/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pista-hardware/propaqm/propaqm.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "propaqm.pb-c.h"
void   propaqm__ident__init
                     (Propaqm__Ident         *message)
{
  static const Propaqm__Ident init_value = PROPAQM__IDENT__INIT;
  *message = init_value;
}
size_t propaqm__ident__get_packed_size
                     (const Propaqm__Ident *message)
{
  assert(message->base.descriptor == &propaqm__ident__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t propaqm__ident__pack
                     (const Propaqm__Ident *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &propaqm__ident__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t propaqm__ident__pack_to_buffer
                     (const Propaqm__Ident *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &propaqm__ident__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Propaqm__Ident *
       propaqm__ident__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Propaqm__Ident *)
     protobuf_c_message_unpack (&propaqm__ident__descriptor,
                                allocator, len, data);
}
void   propaqm__ident__free_unpacked
                     (Propaqm__Ident *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &propaqm__ident__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   propaqm__vitals__init
                     (Propaqm__Vitals         *message)
{
  static const Propaqm__Vitals init_value = PROPAQM__VITALS__INIT;
  *message = init_value;
}
size_t propaqm__vitals__get_packed_size
                     (const Propaqm__Vitals *message)
{
  assert(message->base.descriptor == &propaqm__vitals__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t propaqm__vitals__pack
                     (const Propaqm__Vitals *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &propaqm__vitals__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t propaqm__vitals__pack_to_buffer
                     (const Propaqm__Vitals *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &propaqm__vitals__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Propaqm__Vitals *
       propaqm__vitals__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Propaqm__Vitals *)
     protobuf_c_message_unpack (&propaqm__vitals__descriptor,
                                allocator, len, data);
}
void   propaqm__vitals__free_unpacked
                     (Propaqm__Vitals *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &propaqm__vitals__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   propaqm__sensors__init
                     (Propaqm__Sensors         *message)
{
  static const Propaqm__Sensors init_value = PROPAQM__SENSORS__INIT;
  *message = init_value;
}
size_t propaqm__sensors__get_packed_size
                     (const Propaqm__Sensors *message)
{
  assert(message->base.descriptor == &propaqm__sensors__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t propaqm__sensors__pack
                     (const Propaqm__Sensors *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &propaqm__sensors__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t propaqm__sensors__pack_to_buffer
                     (const Propaqm__Sensors *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &propaqm__sensors__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Propaqm__Sensors *
       propaqm__sensors__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Propaqm__Sensors *)
     protobuf_c_message_unpack (&propaqm__sensors__descriptor,
                                allocator, len, data);
}
void   propaqm__sensors__free_unpacked
                     (Propaqm__Sensors *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &propaqm__sensors__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor propaqm__ident__field_descriptors[2] =
{
  {
    "model",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Ident, model),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_no",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Ident, serial_no),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned propaqm__ident__field_indices_by_name[] = {
  0,   /* field[0] = model */
  1,   /* field[1] = serial_no */
};
static const ProtobufCIntRange propaqm__ident__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor propaqm__ident__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "propaqm.ident",
  "Ident",
  "Propaqm__Ident",
  "propaqm",
  sizeof(Propaqm__Ident),
  2,
  propaqm__ident__field_descriptors,
  propaqm__ident__field_indices_by_name,
  1,  propaqm__ident__number_ranges,
  (ProtobufCMessageInit) propaqm__ident__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor propaqm__vitals__field_descriptors[32] =
{
  {
    "tm",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, tm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "monitored_bits",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, monitored_bits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alarm_bits",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, alarm_bits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "datastate_bits",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, datastate_bits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temp0",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, temp0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temp1",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, temp1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temp2",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, temp2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hr",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, hr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fico2",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, fico2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "patmode",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, patmode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spo2_spco",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, spo2_spco),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spo2_spmet",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, spo2_spmet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spo2_pvi",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, spo2_pvi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spo2_pi",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, spo2_pi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spo2_spoc",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, spo2_spoc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spo2_sphb",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, spo2_sphb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spo2_pct",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, spo2_pct),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nibp_sys",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, nibp_sys),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nibp_dia",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, nibp_dia),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nibp_map",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, nibp_map),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "etco2",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, etco2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp",
    23,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, resp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ibp0_sys",
    30,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, ibp0_sys),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ibp0_dia",
    31,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, ibp0_dia),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ibp0_map",
    32,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, ibp0_map),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ibp1_sys",
    33,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, ibp1_sys),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ibp1_dia",
    34,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, ibp1_dia),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ibp1_map",
    35,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, ibp1_map),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ibp2_sys",
    36,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, ibp2_sys),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ibp2_dia",
    37,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, ibp2_dia),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ibp2_map",
    38,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Vitals, ibp2_map),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned propaqm__vitals__field_indices_by_name[] = {
  3,   /* field[3] = alarm_bits */
  4,   /* field[4] = datastate_bits */
  21,   /* field[21] = etco2 */
  9,   /* field[9] = fico2 */
  8,   /* field[8] = hr */
  24,   /* field[24] = ibp0_dia */
  25,   /* field[25] = ibp0_map */
  23,   /* field[23] = ibp0_sys */
  27,   /* field[27] = ibp1_dia */
  28,   /* field[28] = ibp1_map */
  26,   /* field[26] = ibp1_sys */
  30,   /* field[30] = ibp2_dia */
  31,   /* field[31] = ibp2_map */
  29,   /* field[29] = ibp2_sys */
  2,   /* field[2] = monitored_bits */
  19,   /* field[19] = nibp_dia */
  20,   /* field[20] = nibp_map */
  18,   /* field[18] = nibp_sys */
  10,   /* field[10] = patmode */
  22,   /* field[22] = resp */
  1,   /* field[1] = sid */
  17,   /* field[17] = spo2_pct */
  14,   /* field[14] = spo2_pi */
  13,   /* field[13] = spo2_pvi */
  11,   /* field[11] = spo2_spco */
  16,   /* field[16] = spo2_sphb */
  12,   /* field[12] = spo2_spmet */
  15,   /* field[15] = spo2_spoc */
  5,   /* field[5] = temp0 */
  6,   /* field[6] = temp1 */
  7,   /* field[7] = temp2 */
  0,   /* field[0] = tm */
};
static const ProtobufCIntRange propaqm__vitals__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 30, 23 },
  { 0, 32 }
};
const ProtobufCMessageDescriptor propaqm__vitals__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "propaqm.vitals",
  "Vitals",
  "Propaqm__Vitals",
  "propaqm",
  sizeof(Propaqm__Vitals),
  32,
  propaqm__vitals__field_descriptors,
  propaqm__vitals__field_indices_by_name,
  2,  propaqm__vitals__number_ranges,
  (ProtobufCMessageInit) propaqm__vitals__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor propaqm__sensors__field_descriptors[5] =
{
  {
    "tm",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Sensors, tm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Propaqm__Sensors, sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ecg",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Propaqm__Sensors, n_ecg),
    offsetof(Propaqm__Sensors, ecg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "co2",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Propaqm__Sensors, n_co2),
    offsetof(Propaqm__Sensors, co2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wf3",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Propaqm__Sensors, n_wf3),
    offsetof(Propaqm__Sensors, wf3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned propaqm__sensors__field_indices_by_name[] = {
  3,   /* field[3] = co2 */
  2,   /* field[2] = ecg */
  1,   /* field[1] = sid */
  0,   /* field[0] = tm */
  4,   /* field[4] = wf3 */
};
static const ProtobufCIntRange propaqm__sensors__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor propaqm__sensors__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "propaqm.sensors",
  "Sensors",
  "Propaqm__Sensors",
  "propaqm",
  sizeof(Propaqm__Sensors),
  5,
  propaqm__sensors__field_descriptors,
  propaqm__sensors__field_indices_by_name,
  1,  propaqm__sensors__number_ranges,
  (ProtobufCMessageInit) propaqm__sensors__init,
  NULL,NULL,NULL    /* reserved[123] */
};
