export JAVA_HOME=/opt/jdk/latest
mkdir hdf5_x86-64-1.10.5
cd hdf5_x86-64-1.10.5
#cmake \
 #-Wno-dev \
 #-DBUILD_SHARED_LIBS:BOOL=ON \
 #-DCMAKE_BUILD_TYPE:STRING=Release \
 #-DHDF5_BUILD_HL_LIB:BOOL=ON \
 #-DHDF5_BUILD_FORTRAN:BOOL=OFF \
 #-DHDF5_BUILD_JAVA:BOOL=ON\
 #-DHDF5_ENABLE_F2003:BOOL=OFF \
 #-DHDF5_BUILD_CPP_LIB:BOOL=ON \
 #-DHDF5_BUILD_TOOLS:BOOL=ON \
 #-DCMAKE_Fortran_FLAGS="-cpp" \
 #-G"MSYS Makefiles" \
 #-DCMAKE_INSTALL_PREFIX:PATH="C:/opt/tools/hdf5_1_10_5-rev-dyn-x86-64" \
 #../CMake-hdf5-1.10.5
cmake -Wno-dev -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DHDF5_BUILD_HL_LIB:BOOL=ON -DHDF5_BUILD_FORTRAN:BOOL=OFF -DHDF5_BUILD_JAVA:BOOL=ON -DHDF5_ENABLE_F2003:BOOL=OFF -DHDF5_BUILD_CPP_LIB:BOOL=ON -DHDF5_BUILD_TOOLS:BOOL=ON -DCMAKE_Fortran_FLAGS=-cpp -GMSYS Makefiles -DCMAKE_INSTALL_PREFIX:PATH=C:/opt/tools/hdf5_1_10_5-rev-dyn-x86-64 hdf5-1.10.5
make install
