/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ni_DAQmx_MxTiming */

#ifndef _Included_ni_DAQmx_MxTiming
#define _Included_ni_DAQmx_MxTiming
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ni_DAQmx_MxTiming
 * Method:    configureSampleClock
 * Signature: (Ljava/lang/String;DLni/DAQcommon/SampleClockActiveEdge;Lni/DAQcommon/SampleQuantityMode;I)V
 */
JNIEXPORT void JNICALL Java_ni_DAQmx_MxTiming_configureSampleClock
  (JNIEnv *, jobject, jstring, jdouble, jobject, jobject, jint);

/*
 * Class:     ni_DAQmx_MxTiming
 * Method:    configureOutputBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ni_DAQmx_MxTiming_configureOutputBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     ni_DAQmx_MxTiming
 * Method:    getWriteWaitMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ni_DAQmx_MxTiming_getWriteWaitMode
  (JNIEnv *, jobject);

/*
 * Class:     ni_DAQmx_MxTiming
 * Method:    setWriteWaitMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ni_DAQmx_MxTiming_setWriteWaitMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     ni_DAQmx_MxTiming
 * Method:    resetWriteWaitMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ni_DAQmx_MxTiming_resetWriteWaitMode
  (JNIEnv *, jobject);

/*
 * Class:     ni_DAQmx_MxTiming
 * Method:    getWriteSleepTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ni_DAQmx_MxTiming_getWriteSleepTime
  (JNIEnv *, jobject);

/*
 * Class:     ni_DAQmx_MxTiming
 * Method:    setWriteSleepTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ni_DAQmx_MxTiming_setWriteSleepTime
  (JNIEnv *, jobject);

/*
 * Class:     ni_DAQmx_MxTiming
 * Method:    resetWriteSleepTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ni_DAQmx_MxTiming_resetWriteSleepTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
