/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ni_DAQmx_MxLocal */

#ifndef _Included_ni_DAQmx_MxLocal
#define _Included_ni_DAQmx_MxLocal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ni_DAQmx_MxLocal
 * Method:    getPhysicalChannels
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ni_DAQmx_MxLocal_getPhysicalChannels
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
