/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ni_DAQmx_MxAnalogMultiChannelWriter */

#ifndef _Included_ni_DAQmx_MxAnalogMultiChannelWriter
#define _Included_ni_DAQmx_MxAnalogMultiChannelWriter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
