/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ni_DAQmx_MxAIChannel */

#ifndef _Included_ni_DAQmx_MxAIChannel
#define _Included_ni_DAQmx_MxAIChannel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ni_DAQmx_MxAIChannel
 * Method:    createVoltageChannel
 * Signature: (JLjava/lang/String;Ljava/lang/String;Lni/DAQcommon/AITerminalConfiguration;DDLni/DAQcommon/AIVoltageUnits;)J
 */
JNIEXPORT jlong JNICALL Java_ni_DAQmx_MxAIChannel_createVoltageChannel
  (JNIEnv *, jobject, jlong, jstring, jstring, jobject, jdouble, jdouble, jobject);

#ifdef __cplusplus
}
#endif
#endif
