//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package idea.ts;

import java.util.Date;
import jakarta.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1
    extends XmlAdapter<String, Date>
{


    public Date unmarshal(String value) {
        return (idea.schema.rp.DateTimeAdapter.parseDate(value));
    }

    public String marshal(Date value) {
        return (idea.schema.rp.DateTimeAdapter.printDate(value));
    }

}
