//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.22 at 12:50:03 PM CDT 
//


package idea.ts;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the idea.ts package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TsosessionImpl_QNAME = new QName("http://idea.mil/ts", "tsosession-impl");
    private final static QName _TsoprefsImpl_QNAME = new QName("http://idea.mil/ts", "tsoprefs-impl");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: idea.ts
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TsoPrefs }
     * 
     */
    public TsoPrefs createTsoPrefs() {
        return new TsoPrefs();
    }

    /**
     * Create an instance of {@link TsoSession }
     * 
     */
    public TsoSession createTsoSession() {
        return new TsoSession();
    }

    /**
     * Create an instance of {@link TsoCalibration }
     * 
     */
    public TsoCalibration createTsoCalibration() {
        return new TsoCalibration();
    }

    /**
     * Create an instance of {@link TsCode }
     * 
     */
    public TsCode createTsCode() {
        return new TsCode();
    }

    /**
     * Create an instance of {@link TsoAttributeType }
     * 
     */
    public TsoAttributeType createTsoAttributeType() {
        return new TsoAttributeType();
    }

    /**
     * Create an instance of {@link TsoDeviceType }
     * 
     */
    public TsoDeviceType createTsoDeviceType() {
        return new TsoDeviceType();
    }

    /**
     * Create an instance of {@link TsFilter }
     * 
     */
    public TsFilter createTsFilter() {
        return new TsFilter();
    }

    /**
     * Create an instance of {@link TsoAnnotationEntryType }
     * 
     */
    public TsoAnnotationEntryType createTsoAnnotationEntryType() {
        return new TsoAnnotationEntryType();
    }

    /**
     * Create an instance of {@link TsoSignalLayerType }
     * 
     */
    public TsoSignalLayerType createTsoSignalLayerType() {
        return new TsoSignalLayerType();
    }

    /**
     * Create an instance of {@link TsBand }
     * 
     */
    public TsBand createTsBand() {
        return new TsBand();
    }

    /**
     * Create an instance of {@link TsAnalysis }
     * 
     */
    public TsAnalysis createTsAnalysis() {
        return new TsAnalysis();
    }

    /**
     * Create an instance of {@link TsoPhase }
     * 
     */
    public TsoPhase createTsoPhase() {
        return new TsoPhase();
    }

    /**
     * Create an instance of {@link TsoAnnotationInfoType }
     * 
     */
    public TsoAnnotationInfoType createTsoAnnotationInfoType() {
        return new TsoAnnotationInfoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TsoSession }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://idea.mil/ts", name = "tsosession-impl")
    public JAXBElement<TsoSession> createTsosessionImpl(TsoSession value) {
        return new JAXBElement<TsoSession>(_TsosessionImpl_QNAME, TsoSession.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TsoPrefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://idea.mil/ts", name = "tsoprefs-impl")
    public JAXBElement<TsoPrefs> createTsoprefsImpl(TsoPrefs value) {
        return new JAXBElement<TsoPrefs>(_TsoprefsImpl_QNAME, TsoPrefs.class, null, value);
    }

}
