//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.22 at 12:50:03 PM CDT 
//


package idea.ts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ts-analysis complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ts-analysis">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="analysisClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prefs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eval" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ts-analysis", propOrder = {
    "name",
    "analysisClass",
    "prefs",
    "eval"
})
public class TsAnalysis {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String analysisClass;
    protected String prefs;
    @XmlElement(required = true)
    protected String eval;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the analysisClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnalysisClass() {
        return analysisClass;
    }

    /**
     * Sets the value of the analysisClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnalysisClass(String value) {
        this.analysisClass = value;
    }

    /**
     * Gets the value of the prefs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefs() {
        return prefs;
    }

    /**
     * Sets the value of the prefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefs(String value) {
        this.prefs = value;
    }

    /**
     * Gets the value of the eval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEval() {
        return eval;
    }

    /**
     * Sets the value of the eval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEval(String value) {
        this.eval = value;
    }

}
