//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.22 at 12:50:03 PM CDT 
//


package idea.ts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tso-calibration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tso-calibration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="shift" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="gain" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="offset" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tso-calibration", propOrder = {
    "startTime",
    "shift",
    "gain",
    "offset"
})
public class TsoCalibration {

    protected int startTime;
    protected double shift;
    protected double gain;
    protected double offset;

    /**
     * Gets the value of the startTime property.
     * 
     */
    public int getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     */
    public void setStartTime(int value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the shift property.
     * 
     */
    public double getShift() {
        return shift;
    }

    /**
     * Sets the value of the shift property.
     * 
     */
    public void setShift(double value) {
        this.shift = value;
    }

    /**
     * Gets the value of the gain property.
     * 
     */
    public double getGain() {
        return gain;
    }

    /**
     * Sets the value of the gain property.
     * 
     */
    public void setGain(double value) {
        this.gain = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     */
    public double getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     */
    public void setOffset(double value) {
        this.offset = value;
    }

}
