//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package idea.ts;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.HexBinaryAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tso-signalLayerType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="tso-signalLayerType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="loc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="sidName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="color" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/>
 *         <element name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="ttype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="band_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="attributes" type="{http://idea.mil/ts}tso-attributeType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="calibration" type="{http://idea.mil/ts}tso-calibration" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tso-signalLayerType", propOrder = {
    "loc",
    "name",
    "sidName",
    "color",
    "visible",
    "ttype",
    "bandId",
    "attributes",
    "calibration"
})
public class TsoSignalLayerType {

    @XmlElement(required = true)
    protected String loc;
    protected String name;
    @XmlElement(required = true)
    protected String sidName;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] color;
    protected boolean visible;
    @XmlElement(required = true)
    protected String ttype;
    @XmlElement(name = "band_id")
    protected int bandId;
    protected List<TsoAttributeType> attributes;
    protected List<TsoCalibration> calibration;

    /**
     * Gets the value of the loc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoc() {
        return loc;
    }

    /**
     * Sets the value of the loc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoc(String value) {
        this.loc = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the sidName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSidName() {
        return sidName;
    }

    /**
     * Sets the value of the sidName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSidName(String value) {
        this.sidName = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(byte[] value) {
        this.color = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     */
    public boolean isVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     */
    public void setVisible(boolean value) {
        this.visible = value;
    }

    /**
     * Gets the value of the ttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTtype() {
        return ttype;
    }

    /**
     * Sets the value of the ttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTtype(String value) {
        this.ttype = value;
    }

    /**
     * Gets the value of the bandId property.
     * 
     */
    public int getBandId() {
        return bandId;
    }

    /**
     * Sets the value of the bandId property.
     * 
     */
    public void setBandId(int value) {
        this.bandId = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TsoAttributeType }
     * </p>
     * 
     * 
     * @return
     *     The value of the attributes property.
     */
    public List<TsoAttributeType> getAttributes() {
        if (attributes == null) {
            attributes = new ArrayList<>();
        }
        return this.attributes;
    }

    /**
     * Gets the value of the calibration property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the calibration property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCalibration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TsoCalibration }
     * </p>
     * 
     * 
     * @return
     *     The value of the calibration property.
     */
    public List<TsoCalibration> getCalibration() {
        if (calibration == null) {
            calibration = new ArrayList<>();
        }
        return this.calibration;
    }

}
