//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package idea.ts;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tso-session complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="tso-session">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="dataFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="audioFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="videoFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="dataStart" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         <element name="dataEnd" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         <element name="x-scale" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         <element name="x-translate" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         <element name="activeSignal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="frame-x" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="frame-y" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="frame-width" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="frame-height" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="frame-state" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="tsoBands" type="{http://idea.mil/ts}ts-band" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="tsoDevices" type="{http://idea.mil/ts}tso-deviceType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="tsoAnnotations" type="{http://idea.mil/ts}tso-annotationInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="tsoFilters" type="{http://idea.mil/ts}ts-filter" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="tsoPhases" type="{http://idea.mil/ts}tso-phase" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tso-session", propOrder = {
    "dataFile",
    "audioFile",
    "videoFile",
    "dataStart",
    "dataEnd",
    "xScale",
    "xTranslate",
    "activeSignal",
    "frameX",
    "frameY",
    "frameWidth",
    "frameHeight",
    "frameState",
    "tsoBands",
    "tsoDevices",
    "tsoAnnotations",
    "tsoFilters",
    "tsoPhases"
})
public class TsoSession {

    @XmlElement(required = true)
    protected String dataFile;
    @XmlElement(required = true)
    protected String audioFile;
    @XmlElement(required = true)
    protected String videoFile;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Date dataStart;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Date dataEnd;
    @XmlElement(name = "x-scale")
    protected double xScale;
    @XmlElement(name = "x-translate")
    protected double xTranslate;
    @XmlElement(required = true)
    protected String activeSignal;
    @XmlElement(name = "frame-x")
    protected int frameX;
    @XmlElement(name = "frame-y")
    protected int frameY;
    @XmlElement(name = "frame-width")
    protected int frameWidth;
    @XmlElement(name = "frame-height")
    protected int frameHeight;
    @XmlElement(name = "frame-state")
    protected int frameState;
    protected List<TsBand> tsoBands;
    protected List<TsoDeviceType> tsoDevices;
    protected List<TsoAnnotationInfoType> tsoAnnotations;
    protected List<TsFilter> tsoFilters;
    protected List<TsoPhase> tsoPhases;

    /**
     * Gets the value of the dataFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataFile() {
        return dataFile;
    }

    /**
     * Sets the value of the dataFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataFile(String value) {
        this.dataFile = value;
    }

    /**
     * Gets the value of the audioFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudioFile() {
        return audioFile;
    }

    /**
     * Sets the value of the audioFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudioFile(String value) {
        this.audioFile = value;
    }

    /**
     * Gets the value of the videoFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVideoFile() {
        return videoFile;
    }

    /**
     * Sets the value of the videoFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVideoFile(String value) {
        this.videoFile = value;
    }

    /**
     * Gets the value of the dataStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getDataStart() {
        return dataStart;
    }

    /**
     * Sets the value of the dataStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataStart(Date value) {
        this.dataStart = value;
    }

    /**
     * Gets the value of the dataEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getDataEnd() {
        return dataEnd;
    }

    /**
     * Sets the value of the dataEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataEnd(Date value) {
        this.dataEnd = value;
    }

    /**
     * Gets the value of the xScale property.
     * 
     */
    public double getXScale() {
        return xScale;
    }

    /**
     * Sets the value of the xScale property.
     * 
     */
    public void setXScale(double value) {
        this.xScale = value;
    }

    /**
     * Gets the value of the xTranslate property.
     * 
     */
    public double getXTranslate() {
        return xTranslate;
    }

    /**
     * Sets the value of the xTranslate property.
     * 
     */
    public void setXTranslate(double value) {
        this.xTranslate = value;
    }

    /**
     * Gets the value of the activeSignal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveSignal() {
        return activeSignal;
    }

    /**
     * Sets the value of the activeSignal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveSignal(String value) {
        this.activeSignal = value;
    }

    /**
     * Gets the value of the frameX property.
     * 
     */
    public int getFrameX() {
        return frameX;
    }

    /**
     * Sets the value of the frameX property.
     * 
     */
    public void setFrameX(int value) {
        this.frameX = value;
    }

    /**
     * Gets the value of the frameY property.
     * 
     */
    public int getFrameY() {
        return frameY;
    }

    /**
     * Sets the value of the frameY property.
     * 
     */
    public void setFrameY(int value) {
        this.frameY = value;
    }

    /**
     * Gets the value of the frameWidth property.
     * 
     */
    public int getFrameWidth() {
        return frameWidth;
    }

    /**
     * Sets the value of the frameWidth property.
     * 
     */
    public void setFrameWidth(int value) {
        this.frameWidth = value;
    }

    /**
     * Gets the value of the frameHeight property.
     * 
     */
    public int getFrameHeight() {
        return frameHeight;
    }

    /**
     * Sets the value of the frameHeight property.
     * 
     */
    public void setFrameHeight(int value) {
        this.frameHeight = value;
    }

    /**
     * Gets the value of the frameState property.
     * 
     */
    public int getFrameState() {
        return frameState;
    }

    /**
     * Sets the value of the frameState property.
     * 
     */
    public void setFrameState(int value) {
        this.frameState = value;
    }

    /**
     * Gets the value of the tsoBands property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tsoBands property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTsoBands().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TsBand }
     * </p>
     * 
     * 
     * @return
     *     The value of the tsoBands property.
     */
    public List<TsBand> getTsoBands() {
        if (tsoBands == null) {
            tsoBands = new ArrayList<>();
        }
        return this.tsoBands;
    }

    /**
     * Gets the value of the tsoDevices property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tsoDevices property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTsoDevices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TsoDeviceType }
     * </p>
     * 
     * 
     * @return
     *     The value of the tsoDevices property.
     */
    public List<TsoDeviceType> getTsoDevices() {
        if (tsoDevices == null) {
            tsoDevices = new ArrayList<>();
        }
        return this.tsoDevices;
    }

    /**
     * Gets the value of the tsoAnnotations property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tsoAnnotations property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTsoAnnotations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TsoAnnotationInfoType }
     * </p>
     * 
     * 
     * @return
     *     The value of the tsoAnnotations property.
     */
    public List<TsoAnnotationInfoType> getTsoAnnotations() {
        if (tsoAnnotations == null) {
            tsoAnnotations = new ArrayList<>();
        }
        return this.tsoAnnotations;
    }

    /**
     * Gets the value of the tsoFilters property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tsoFilters property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTsoFilters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TsFilter }
     * </p>
     * 
     * 
     * @return
     *     The value of the tsoFilters property.
     */
    public List<TsFilter> getTsoFilters() {
        if (tsoFilters == null) {
            tsoFilters = new ArrayList<>();
        }
        return this.tsoFilters;
    }

    /**
     * Gets the value of the tsoPhases property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tsoPhases property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTsoPhases().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TsoPhase }
     * </p>
     * 
     * 
     * @return
     *     The value of the tsoPhases property.
     */
    public List<TsoPhase> getTsoPhases() {
        if (tsoPhases == null) {
            tsoPhases = new ArrayList<>();
        }
        return this.tsoPhases;
    }

}
