//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.12 at 08:57:32 AM CDT 
//


package idea.schema.rp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rp-bandData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rp-bandData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bandNum" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bandAttr" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bandWeight" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="waveformSetup" type="{http://idea.mil/rp}rp-waveformSetup" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rp-bandData", propOrder = {
    "bandNum",
    "bandAttr",
    "bandWeight",
    "waveformSetup"
})
public class RpBandData {

    protected int bandNum;
    protected int bandAttr;
    protected int bandWeight;
    protected List<RpWaveformSetup> waveformSetup;

    /**
     * Gets the value of the bandNum property.
     * 
     */
    public int getBandNum() {
        return bandNum;
    }

    /**
     * Sets the value of the bandNum property.
     * 
     */
    public void setBandNum(int value) {
        this.bandNum = value;
    }

    /**
     * Gets the value of the bandAttr property.
     * 
     */
    public int getBandAttr() {
        return bandAttr;
    }

    /**
     * Sets the value of the bandAttr property.
     * 
     */
    public void setBandAttr(int value) {
        this.bandAttr = value;
    }

    /**
     * Gets the value of the bandWeight property.
     * 
     */
    public int getBandWeight() {
        return bandWeight;
    }

    /**
     * Sets the value of the bandWeight property.
     * 
     */
    public void setBandWeight(int value) {
        this.bandWeight = value;
    }

    /**
     * Gets the value of the waveformSetup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the waveformSetup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWaveformSetup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RpWaveformSetup }
     * 
     * 
     */
    public List<RpWaveformSetup> getWaveformSetup() {
        if (waveformSetup == null) {
            waveformSetup = new ArrayList<RpWaveformSetup>();
        }
        return this.waveformSetup;
    }

}
