//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package idea.schema.rp;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for rp-connType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="rp-connType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="RS_232"/>
 *     <enumeration value="Ethernet"/>
 *     <enumeration value="Proxy"/>
 *     <enumeration value="Phidget"/>
 *     <enumeration value="Infinity"/>
 *     <enumeration value="DAQmx"/>
 *     <enumeration value="DAQmxBase"/>
 *     <enumeration value="SEALINK"/>
 *     <enumeration value="LabJack"/>
 *     <enumeration value="MCCUL"/>
 *     <enumeration value="DT"/>
 *     <enumeration value="Intellivue"/>
 *     <enumeration value="PropaqM"/>
 *     <enumeration value="I2C"/>
 *     <enumeration value="None"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "rp-connType")
@XmlEnum
public enum RpConnType {

    RS_232("RS_232"),
    @XmlEnumValue("Ethernet")
    ETHERNET("Ethernet"),
    @XmlEnumValue("Proxy")
    PROXY("Proxy"),
    @XmlEnumValue("Phidget")
    PHIDGET("Phidget"),
    @XmlEnumValue("Infinity")
    INFINITY("Infinity"),
    @XmlEnumValue("DAQmx")
    DA_QMX("DAQmx"),
    @XmlEnumValue("DAQmxBase")
    DA_QMX_BASE("DAQmxBase"),
    SEALINK("SEALINK"),
    @XmlEnumValue("LabJack")
    LAB_JACK("LabJack"),
    MCCUL("MCCUL"),
    DT("DT"),
    @XmlEnumValue("Intellivue")
    INTELLIVUE("Intellivue"),
    @XmlEnumValue("PropaqM")
    PROPAQ_M("PropaqM"),
    @XmlEnumValue("I2C")
    I_2_C("I2C"),
    @XmlEnumValue("None")
    NONE("None");
    private final String value;

    RpConnType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static RpConnType fromValue(String v) {
        for (RpConnType c: RpConnType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
