//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.28 at 11:39:49 AM CDT 
//


package idea.schema.rp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rp-device complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rp-device">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="revNo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="driverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deviceClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="connectionType" type="{http://idea.mil/rp}rp-connType"/>
 *         &lt;element name="connectionValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="param" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="streams" type="{http://idea.mil/rp}rp-stream" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="devices" type="{http://idea.mil/rp}rp-device" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rp-device", propOrder = {
    "name",
    "revNo",
    "driverName",
    "modelName",
    "deviceClass",
    "connectionType",
    "connectionValue",
    "param",
    "streams",
    "devices"
})
public class RpDevice<T extends RpStream> {

    @XmlElement(required = true)
    protected String name;
    protected int revNo;
    @XmlElement(required = true)
    protected String driverName;
    @XmlElement(required = true)
    protected String modelName;
    @XmlElement(required = true)
    protected String deviceClass;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected RpConnType connectionType;
    @XmlElement(required = true)
    protected String connectionValue;
    @XmlElement(required = true, type = Integer.class)
    protected StringStringMap param;
    protected List<T> streams;
    protected List<RpDevice> devices;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the revNo property.
     * 
     */
    public int getRevNo() {
        return revNo;
    }

    /**
     * Sets the value of the revNo property.
     * 
     */
    public void setRevNo(int value) {
        this.revNo = value;
    }

    /**
     * Gets the value of the driverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * Sets the value of the driverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverName(String value) {
        this.driverName = value;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the deviceClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceClass() {
        return deviceClass;
    }

    /**
     * Sets the value of the deviceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceClass(String value) {
        this.deviceClass = value;
    }

    /**
     * Gets the value of the connectionType property.
     * 
     * @return
     *     possible object is
     *     {@link RpConnType }
     *     
     */
    public RpConnType getConnectionType() {
        return connectionType;
    }

    /**
     * Sets the value of the connectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpConnType }
     *     
     */
    public void setConnectionType(RpConnType value) {
        this.connectionType = value;
    }

    /**
     * Gets the value of the connectionValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionValue() {
        return connectionValue;
    }

    /**
     * Sets the value of the connectionValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionValue(String value) {
        this.connectionValue = value;
    }

    /**
     * Gets the value of the param property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public StringStringMap getParam() {
        return param;
    }

    /**
     * Sets the value of the param property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setParam(StringStringMap value) {
        this.param = value;
    }

    /**
     * Gets the value of the streams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the streams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStreams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RpStream }
     * 
     * 
     */
    public List<T> getStreams() {
        if (streams == null) {
            streams = new ArrayList<T>();
        }
        return this.streams;
    }

    /**
     * Gets the value of the devices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the devices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDevices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RpDevice }
     * 
     * 
     */
    public List<RpDevice> getDevices() {
        if (devices == null) {
            devices = new ArrayList<RpDevice>();
        }
        return this.devices;
    }

}
