//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package idea.schema.rp;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rp-device complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="rp-device">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="revNo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="driverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="modelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="deviceClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="connectionType" type="{http://idea.mil/rp}rp-connType"/>
 *         <element name="connectionValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="param" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="streams" type="{http://idea.mil/rp}rp-stream" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="devices" type="{http://idea.mil/rp}rp-device" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rp-device", propOrder = {
    "name",
    "revNo",
    "driverName",
    "modelName",
    "deviceClass",
    "connectionType",
    "connectionValue",
    "param",
    "streams",
    "devices"
})
public class RpDevice {

    @XmlElement(required = true)
    protected String name;
    protected int revNo;
    @XmlElement(required = true)
    protected String driverName;
    @XmlElement(required = true)
    protected String modelName;
    @XmlElement(required = true)
    protected String deviceClass;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected RpConnType connectionType;
    @XmlElement(required = true)
    protected String connectionValue;
    @XmlElement(required = true, type = Integer.class)
    protected StringStringMap param;
    protected List<RpStream> streams;
    protected List<RpDevice> devices;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the revNo property.
     * 
     */
    public int getRevNo() {
        return revNo;
    }

    /**
     * Sets the value of the revNo property.
     * 
     */
    public void setRevNo(int value) {
        this.revNo = value;
    }

    /**
     * Gets the value of the driverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * Sets the value of the driverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverName(String value) {
        this.driverName = value;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the deviceClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceClass() {
        return deviceClass;
    }

    /**
     * Sets the value of the deviceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceClass(String value) {
        this.deviceClass = value;
    }

    /**
     * Gets the value of the connectionType property.
     * 
     * @return
     *     possible object is
     *     {@link RpConnType }
     *     
     */
    public RpConnType getConnectionType() {
        return connectionType;
    }

    /**
     * Sets the value of the connectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpConnType }
     *     
     */
    public void setConnectionType(RpConnType value) {
        this.connectionType = value;
    }

    /**
     * Gets the value of the connectionValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionValue() {
        return connectionValue;
    }

    /**
     * Sets the value of the connectionValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionValue(String value) {
        this.connectionValue = value;
    }

    /**
     * Gets the value of the param property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public StringStringMap getParam() {
        return param;
    }

    /**
     * Sets the value of the param property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setParam(StringStringMap value) {
        this.param = value;
    }

    /**
     * Gets the value of the streams property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the streams property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getStreams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RpStream }
     * </p>
     * 
     * 
     * @return
     *     The value of the streams property.
     */
    public List<RpStream> getStreams() {
        if (streams == null) {
            streams = new ArrayList<>();
        }
        return this.streams;
    }

    /**
     * Gets the value of the devices property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the devices property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getDevices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RpDevice }
     * </p>
     * 
     * 
     * @return
     *     The value of the devices property.
     */
    public List<RpDevice> getDevices() {
        if (devices == null) {
            devices = new ArrayList<>();
        }
        return this.devices;
    }

}
