//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package idea.schema.rp;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rp-display complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="rp-display">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="numBands" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="numPBoxes" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="horizPBoxes" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="vertPBoxes" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="opmode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="bandData" type="{http://idea.mil/rp}rp-bandData" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="pboxData" type="{http://idea.mil/rp}rp-pboxData" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rp-display", propOrder = {
    "numBands",
    "numPBoxes",
    "horizPBoxes",
    "vertPBoxes",
    "opmode",
    "bandData",
    "pboxData"
})
public class RpDisplay {

    protected int numBands;
    protected int numPBoxes;
    protected int horizPBoxes;
    protected int vertPBoxes;
    protected int opmode;
    protected List<RpBandData> bandData;
    protected List<RpPboxData> pboxData;

    /**
     * Gets the value of the numBands property.
     * 
     */
    public int getNumBands() {
        return numBands;
    }

    /**
     * Sets the value of the numBands property.
     * 
     */
    public void setNumBands(int value) {
        this.numBands = value;
    }

    /**
     * Gets the value of the numPBoxes property.
     * 
     */
    public int getNumPBoxes() {
        return numPBoxes;
    }

    /**
     * Sets the value of the numPBoxes property.
     * 
     */
    public void setNumPBoxes(int value) {
        this.numPBoxes = value;
    }

    /**
     * Gets the value of the horizPBoxes property.
     * 
     */
    public int getHorizPBoxes() {
        return horizPBoxes;
    }

    /**
     * Sets the value of the horizPBoxes property.
     * 
     */
    public void setHorizPBoxes(int value) {
        this.horizPBoxes = value;
    }

    /**
     * Gets the value of the vertPBoxes property.
     * 
     */
    public int getVertPBoxes() {
        return vertPBoxes;
    }

    /**
     * Sets the value of the vertPBoxes property.
     * 
     */
    public void setVertPBoxes(int value) {
        this.vertPBoxes = value;
    }

    /**
     * Gets the value of the opmode property.
     * 
     */
    public int getOpmode() {
        return opmode;
    }

    /**
     * Sets the value of the opmode property.
     * 
     */
    public void setOpmode(int value) {
        this.opmode = value;
    }

    /**
     * Gets the value of the bandData property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bandData property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getBandData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RpBandData }
     * </p>
     * 
     * 
     * @return
     *     The value of the bandData property.
     */
    public List<RpBandData> getBandData() {
        if (bandData == null) {
            bandData = new ArrayList<>();
        }
        return this.bandData;
    }

    /**
     * Gets the value of the pboxData property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pboxData property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getPboxData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RpPboxData }
     * </p>
     * 
     * 
     * @return
     *     The value of the pboxData property.
     */
    public List<RpPboxData> getPboxData() {
        if (pboxData == null) {
            pboxData = new ArrayList<>();
        }
        return this.pboxData;
    }

}
