//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package idea.schema.rp;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rp-linear-unit complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="rp-linear-unit">
 *   <complexContent>
 *     <extension base="{http://idea.mil/rp}rp-unit">
 *       <sequence>
 *         <element name="m" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         <element name="b" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rp-linear-unit", propOrder = {
    "m",
    "b"
})
public class RpLinearUnit
    extends RpUnit
{

    protected double m;
    protected double b;

    /**
     * Gets the value of the m property.
     * 
     */
    public double getM() {
        return m;
    }

    /**
     * Sets the value of the m property.
     * 
     */
    public void setM(double value) {
        this.m = value;
    }

    /**
     * Gets the value of the b property.
     * 
     */
    public double getB() {
        return b;
    }

    /**
     * Sets the value of the b property.
     * 
     */
    public void setB(double value) {
        this.b = value;
    }
    

	public static RpLinearUnit unit = new RpLinearUnit( 1.0, 0.0, "");
			
	public RpLinearUnit() { }
	public RpLinearUnit(double m, double b, String name) {
		setM(m);
		setB(b);
		setUnitName(name);
	}

	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof RpLinearUnit)) {
			return false;
		}
		RpLinearUnit u = (RpLinearUnit) obj;
		if (m != u.m) {
			return false;
		}
		if (b != u.b) {
			return false;
		}
		return unitName.equals(u.unitName);
	}

	public double transform(int	val) { return m*val + b; }
	public int inverse(double val) { return	(int)((val - b)/m + 0.5); }  // simple rounding method via truncation
	public double transform_d(double	val) { return m*val + b; }
	public double inverse_d(double val) { return	((val - b)/m); }
	
	@Override
	public String toString() {	return unitName + "[" + m + "," + b + "]"; }

			
			
}
