//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.12 at 08:57:32 AM CDT 
//


package idea.schema.rp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rp-linear-unit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rp-linear-unit">
 *   &lt;complexContent>
 *     &lt;extension base="{http://idea.mil/rp}rp-unit">
 *       &lt;sequence>
 *         &lt;element name="m" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="b" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rp-linear-unit", propOrder = {
    "m",
    "b"
})
public class RpLinearUnit
    extends RpUnit
{

    protected double m;
    protected double b;

    /**
     * Gets the value of the m property.
     * 
     */
    public double getM() {
        return m;
    }

    /**
     * Sets the value of the m property.
     * 
     */
    public void setM(double value) {
        this.m = value;
    }

    /**
     * Gets the value of the b property.
     * 
     */
    public double getB() {
        return b;
    }

    /**
     * Sets the value of the b property.
     * 
     */
    public void setB(double value) {
        this.b = value;
    }
    

	public static RpLinearUnit unit = new RpLinearUnit( 1.0, 0.0, "");
			
	public RpLinearUnit() { }
	public RpLinearUnit(double m, double b, String name) {
		setM(m);
		setB(b);
		setUnitName(name);
	}

	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof RpLinearUnit)) {
			return false;
		}
		RpLinearUnit u = (RpLinearUnit) obj;
		if (m != u.m) {
			return false;
		}
		if (b != u.b) {
			return false;
		}
		return unitName.equals(u.unitName);
	}

	public double transform(int	val) { return m*val + b; }
	public int inverse(double val) { return	(int)((val - b)/m + 0.5); }  // simple rounding method via truncation
	public double transform_d(double	val) { return m*val + b; }
	public double inverse_d(double val) { return	((val - b)/m); }
	
	@Override
	public String toString() {	return unitName + "[" + m + "," + b + "]"; }

			
			
}
