//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package idea.schema.rp;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rp-metric complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="rp-metric">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="subtyp" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         <element name="unit" type="{http://idea.mil/rp}rp-unit"/>
 *         <element name="sample-rate" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         <element name="samples-per-packet" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rp-metric", propOrder = {
    "name",
    "code",
    "location",
    "subtyp",
    "unit",
    "sampleRate",
    "samplesPerPacket"
})
public class RpMetric {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String code;
    @XmlElement(required = true)
    protected String location;
    protected Integer subtyp;
    @XmlElement(required = true)
    protected RpUnit unit;
    @XmlElement(name = "sample-rate")
    protected Integer sampleRate;
    @XmlElement(name = "samples-per-packet")
    protected Integer samplesPerPacket;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the subtyp property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSubtyp() {
        return subtyp;
    }

    /**
     * Sets the value of the subtyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSubtyp(Integer value) {
        this.subtyp = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link RpUnit }
     *     
     */
    public RpUnit getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpUnit }
     *     
     */
    public void setUnit(RpUnit value) {
        this.unit = value;
    }

    /**
     * Gets the value of the sampleRate property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSampleRate() {
        return sampleRate;
    }

    /**
     * Sets the value of the sampleRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSampleRate(Integer value) {
        this.sampleRate = value;
    }

    /**
     * Gets the value of the samplesPerPacket property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSamplesPerPacket() {
        return samplesPerPacket;
    }

    /**
     * Sets the value of the samplesPerPacket property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSamplesPerPacket(Integer value) {
        this.samplesPerPacket = value;
    }
    

				public RpMetric() {}
				public RpMetric( String loc, String code, String name, RpUnit u, int subtyp ) {
					setLocation(loc);
					setCode( code );
					setName( name );
					setUnit( u );
					setSubtyp( subtyp );
				}
		
				public String getUnitName() { return (unit == null) ? "" : unit.getUnitName(); }
				
				@jakarta.xml.bind.annotation.XmlTransient
				public java.lang.reflect.Method getter;
				@jakarta.xml.bind.annotation.XmlTransient
				public java.lang.reflect.Method setter;
				
				@jakarta.xml.bind.annotation.XmlTransient				
				public java.lang.String h5FieldName;
				public String getH5FieldName() {
					return h5FieldName;
				}
				public void setH5FieldName(String val) {
					h5FieldName = val;
				}
				
				@jakarta.xml.bind.annotation.XmlTransient
				private boolean active;
				public void setActive( boolean b ) { active = b; }
				public boolean isActive( ) { return active; }
				
				public String getAlias() {
					String alias = getName();
					if( alias == null || alias.length() == 0 ) {
						alias = getCode();
					}
					if( alias == null || alias.length() == 0 ) {
						alias = getLocation();
					}
		
					return alias;
				}
				

				 
			
}
