//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.12 at 08:57:32 AM CDT 
//


package idea.schema.rp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rp-pboxData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rp-pboxData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pboxId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="pboxFormat" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="pboxWeight" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="foreground" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="paramSetup" type="{http://idea.mil/rp}rp-metric" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rp-pboxData", propOrder = {
    "pboxId",
    "pboxFormat",
    "pboxWeight",
    "foreground",
    "paramSetup"
})
public class RpPboxData {

    protected int pboxId;
    protected int pboxFormat;
    protected int pboxWeight;
    protected int foreground;
    protected List<RpMetric> paramSetup;

    /**
     * Gets the value of the pboxId property.
     * 
     */
    public int getPboxId() {
        return pboxId;
    }

    /**
     * Sets the value of the pboxId property.
     * 
     */
    public void setPboxId(int value) {
        this.pboxId = value;
    }

    /**
     * Gets the value of the pboxFormat property.
     * 
     */
    public int getPboxFormat() {
        return pboxFormat;
    }

    /**
     * Sets the value of the pboxFormat property.
     * 
     */
    public void setPboxFormat(int value) {
        this.pboxFormat = value;
    }

    /**
     * Gets the value of the pboxWeight property.
     * 
     */
    public int getPboxWeight() {
        return pboxWeight;
    }

    /**
     * Sets the value of the pboxWeight property.
     * 
     */
    public void setPboxWeight(int value) {
        this.pboxWeight = value;
    }

    /**
     * Gets the value of the foreground property.
     * 
     */
    public int getForeground() {
        return foreground;
    }

    /**
     * Sets the value of the foreground property.
     * 
     */
    public void setForeground(int value) {
        this.foreground = value;
    }

    /**
     * Gets the value of the paramSetup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paramSetup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParamSetup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RpMetric }
     * 
     * 
     */
    public List<RpMetric> getParamSetup() {
        if (paramSetup == null) {
            paramSetup = new ArrayList<RpMetric>();
        }
        return this.paramSetup;
    }

}
