//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package idea.schema.rp;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rp-precision-unit complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="rp-precision-unit">
 *   <complexContent>
 *     <extension base="{http://idea.mil/rp}rp-unit">
 *       <sequence>
 *         <element name="precision" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rp-precision-unit", propOrder = {
    "precision"
})
public class RpPrecisionUnit
    extends RpUnit
{

    protected int precision;

    /**
     * Gets the value of the precision property.
     * 
     */
    public int getPrecision() {
        return precision;
    }

    /**
     * Sets the value of the precision property.
     * 
     */
    public void setPrecision(int value) {
        this.precision = value;
    }
    

				public RpPrecisionUnit() { }
				public RpPrecisionUnit(int	p, String u) {
					setPrecision( p );
					setUnitName( u );
				}
				
				public double transform(int val) {
				int p = precision;
				double v = val;
				while (p > 0) {	v = v / 10;	p--; }
				while (p < 0) {	v = v * 10;	p++; }
				return v;
				}

				public int inverse(double val) {
				int p = precision;
				while( p > 0 ) { val *= 10.0; p--;	}
				while( p < 0 ) { val /= 10.0; p++;	}
				return (int)(val + .5);
				}
				
				@Override
				public String toString() {	return unitName + "[" + precision + "]"; }
	private static double transform_d(double val, int p) {
		double v = val;
		while (p > 0) {
			v = v / 10;
			p--;
		}
		while (p < 0) {
			v = v * 10;
			p++;
		}
		return v;
	}

	public double transform_d(double val) {
		return transform_d( val, precision );
	}
	public double inverse_d(double val) {
		return transform_d( val, -precision );
	}

				
			
}
