//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.12 at 08:57:32 AM CDT 
//


package idea.schema.rp;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rp-resourceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="rp-resourceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="H5_DATAFILE"/>
 *     &lt;enumeration value="RDB_DATASET"/>
 *     &lt;enumeration value="X_DOCUMENT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "rp-resourceType")
@XmlEnum
public enum RpResourceType {

    @XmlEnumValue("H5_DATAFILE")
    H_5_DATAFILE("H5_DATAFILE"),
    RDB_DATASET("RDB_DATASET"),
    X_DOCUMENT("X_DOCUMENT");
    private final String value;

    RpResourceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RpResourceType fromValue(String v) {
        for (RpResourceType c: RpResourceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
