//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package idea.schema.rp;

import java.util.Date;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for rp-subject complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="rp-subject">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="branch" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="dataType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="studyTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="surgeryDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         <element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="medicalId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="baseFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="operator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="seqNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rp-subject", propOrder = {
    "identifier",
    "branch",
    "company",
    "organization",
    "location",
    "dataType",
    "studyTitle",
    "surgeryDate",
    "subject",
    "medicalId",
    "baseFileName",
    "operator",
    "seqNo",
    "notes"
})
public class RpSubject {

    @XmlElement(required = true)
    protected String identifier;
    @XmlElement(required = true)
    protected String branch;
    @XmlElement(required = true)
    protected String company;
    @XmlElement(required = true)
    protected String organization;
    @XmlElement(required = true)
    protected String location;
    protected int dataType;
    @XmlElement(required = true)
    protected String studyTitle;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Date surgeryDate;
    @XmlElement(required = true)
    protected String subject;
    @XmlElement(required = true)
    protected String medicalId;
    @XmlElement(required = true)
    protected String baseFileName;
    @XmlElement(required = true)
    protected String operator;
    @XmlElement(required = true)
    protected String seqNo;
    @XmlElement(required = true)
    protected String notes;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the branch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranch() {
        return branch;
    }

    /**
     * Sets the value of the branch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranch(String value) {
        this.branch = value;
    }

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompany(String value) {
        this.company = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganization(String value) {
        this.organization = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the dataType property.
     * 
     */
    public int getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     */
    public void setDataType(int value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the studyTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudyTitle() {
        return studyTitle;
    }

    /**
     * Sets the value of the studyTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudyTitle(String value) {
        this.studyTitle = value;
    }

    /**
     * Gets the value of the surgeryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getSurgeryDate() {
        return surgeryDate;
    }

    /**
     * Sets the value of the surgeryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurgeryDate(Date value) {
        this.surgeryDate = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the medicalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicalId() {
        return medicalId;
    }

    /**
     * Sets the value of the medicalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicalId(String value) {
        this.medicalId = value;
    }

    /**
     * Gets the value of the baseFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseFileName() {
        return baseFileName;
    }

    /**
     * Sets the value of the baseFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseFileName(String value) {
        this.baseFileName = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperator(String value) {
        this.operator = value;
    }

    /**
     * Gets the value of the seqNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqNo(String value) {
        this.seqNo = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

}
