//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.12 at 08:57:32 AM CDT 
//


package idea.schema.rp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rp-unit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rp-unit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unitName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cached-typ" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rp-unit", propOrder = {
    "unitName",
    "cachedTyp"
})
@XmlSeeAlso({
    RpPrecisionUnit.class,
    RpLinearUnit.class
})
public abstract class RpUnit {

    @XmlElement(required = true)
    protected String unitName;
    @XmlElement(name = "cached-typ")
    protected int cachedTyp;

    /**
     * Gets the value of the unitName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * Sets the value of the unitName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitName(String value) {
        this.unitName = value;
    }

    /**
     * Gets the value of the cachedTyp property.
     * 
     */
    public int getCachedTyp() {
        return cachedTyp;
    }

    /**
     * Sets the value of the cachedTyp property.
     * 
     */
    public void setCachedTyp(int value) {
        this.cachedTyp = value;
    }
    

				public abstract double transform(int val);
				public abstract	int inverse(double val);
				
				public abstract double transform_d(double val);
				public abstract	double inverse_d(double val);

			
}
