//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package idea.schema.rp;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rp-waveformSetup complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="rp-waveformSetup">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="sweepSpeed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="sampleRate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="rangeMin" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="rangeMax" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="signalGroup" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="signalId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="waveColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="loc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rp-waveformSetup", propOrder = {
    "sweepSpeed",
    "sampleRate",
    "rangeMin",
    "rangeMax",
    "signalGroup",
    "signalId",
    "waveColor",
    "loc"
})
public class RpWaveformSetup {

    protected int sweepSpeed;
    protected int sampleRate;
    protected int rangeMin;
    protected int rangeMax;
    @XmlElement(required = true)
    protected String signalGroup;
    @XmlElement(required = true)
    protected String signalId;
    @XmlElement(required = true)
    protected String waveColor;
    @XmlElement(required = true)
    protected String loc;

    /**
     * Gets the value of the sweepSpeed property.
     * 
     */
    public int getSweepSpeed() {
        return sweepSpeed;
    }

    /**
     * Sets the value of the sweepSpeed property.
     * 
     */
    public void setSweepSpeed(int value) {
        this.sweepSpeed = value;
    }

    /**
     * Gets the value of the sampleRate property.
     * 
     */
    public int getSampleRate() {
        return sampleRate;
    }

    /**
     * Sets the value of the sampleRate property.
     * 
     */
    public void setSampleRate(int value) {
        this.sampleRate = value;
    }

    /**
     * Gets the value of the rangeMin property.
     * 
     */
    public int getRangeMin() {
        return rangeMin;
    }

    /**
     * Sets the value of the rangeMin property.
     * 
     */
    public void setRangeMin(int value) {
        this.rangeMin = value;
    }

    /**
     * Gets the value of the rangeMax property.
     * 
     */
    public int getRangeMax() {
        return rangeMax;
    }

    /**
     * Sets the value of the rangeMax property.
     * 
     */
    public void setRangeMax(int value) {
        this.rangeMax = value;
    }

    /**
     * Gets the value of the signalGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignalGroup() {
        return signalGroup;
    }

    /**
     * Sets the value of the signalGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignalGroup(String value) {
        this.signalGroup = value;
    }

    /**
     * Gets the value of the signalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignalId() {
        return signalId;
    }

    /**
     * Sets the value of the signalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignalId(String value) {
        this.signalId = value;
    }

    /**
     * Gets the value of the waveColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaveColor() {
        return waveColor;
    }

    /**
     * Sets the value of the waveColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaveColor(String value) {
        this.waveColor = value;
    }

    /**
     * Gets the value of the loc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoc() {
        return loc;
    }

    /**
     * Sets the value of the loc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoc(String value) {
        this.loc = value;
    }

}
