/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: model/bmp180.proto */

#ifndef PROTOBUF_C_model_2fbmp180_2eproto__INCLUDED
#define PROTOBUF_C_model_2fbmp180_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Bmp180__Measurement Bmp180__Measurement;


/* --- enums --- */


/* --- messages --- */

struct  _Bmp180__Measurement
{
  ProtobufCMessage base;
  int64_t tm;
  float t;
  float p;
};
#define BMP180__MEASUREMENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bmp180__measurement__descriptor) \
    , 0, 0, 0 }


/* Bmp180__Measurement methods */
void   bmp180__measurement__init
                     (Bmp180__Measurement         *message);
size_t bmp180__measurement__get_packed_size
                     (const Bmp180__Measurement   *message);
size_t bmp180__measurement__pack
                     (const Bmp180__Measurement   *message,
                      uint8_t             *out);
size_t bmp180__measurement__pack_to_buffer
                     (const Bmp180__Measurement   *message,
                      ProtobufCBuffer     *buffer);
Bmp180__Measurement *
       bmp180__measurement__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bmp180__measurement__free_unpacked
                     (Bmp180__Measurement *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Bmp180__Measurement_Closure)
                 (const Bmp180__Measurement *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor bmp180__measurement__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_model_2fbmp180_2eproto__INCLUDED */
