/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pista-hardware/simu/simu.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pista-hardware/simu/simu.pb-c.h"
void   simu__simu_settings__init
                     (Simu__SimuSettings         *message)
{
  static const Simu__SimuSettings init_value = SIMU__SIMU_SETTINGS__INIT;
  *message = init_value;
}
size_t simu__simu_settings__get_packed_size
                     (const Simu__SimuSettings *message)
{
  assert(message->base.descriptor == &simu__simu_settings__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t simu__simu_settings__pack
                     (const Simu__SimuSettings *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &simu__simu_settings__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t simu__simu_settings__pack_to_buffer
                     (const Simu__SimuSettings *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &simu__simu_settings__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Simu__SimuSettings *
       simu__simu_settings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Simu__SimuSettings *)
     protobuf_c_message_unpack (&simu__simu_settings__descriptor,
                                allocator, len, data);
}
void   simu__simu_settings__free_unpacked
                     (Simu__SimuSettings *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &simu__simu_settings__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   simu__simu_vitals__init
                     (Simu__SimuVitals         *message)
{
  static const Simu__SimuVitals init_value = SIMU__SIMU_VITALS__INIT;
  *message = init_value;
}
size_t simu__simu_vitals__get_packed_size
                     (const Simu__SimuVitals *message)
{
  assert(message->base.descriptor == &simu__simu_vitals__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t simu__simu_vitals__pack
                     (const Simu__SimuVitals *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &simu__simu_vitals__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t simu__simu_vitals__pack_to_buffer
                     (const Simu__SimuVitals *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &simu__simu_vitals__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Simu__SimuVitals *
       simu__simu_vitals__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Simu__SimuVitals *)
     protobuf_c_message_unpack (&simu__simu_vitals__descriptor,
                                allocator, len, data);
}
void   simu__simu_vitals__free_unpacked
                     (Simu__SimuVitals *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &simu__simu_vitals__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   simu__simu_waveform__init
                     (Simu__SimuWaveform         *message)
{
  static const Simu__SimuWaveform init_value = SIMU__SIMU_WAVEFORM__INIT;
  *message = init_value;
}
size_t simu__simu_waveform__get_packed_size
                     (const Simu__SimuWaveform *message)
{
  assert(message->base.descriptor == &simu__simu_waveform__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t simu__simu_waveform__pack
                     (const Simu__SimuWaveform *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &simu__simu_waveform__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t simu__simu_waveform__pack_to_buffer
                     (const Simu__SimuWaveform *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &simu__simu_waveform__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Simu__SimuWaveform *
       simu__simu_waveform__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Simu__SimuWaveform *)
     protobuf_c_message_unpack (&simu__simu_waveform__descriptor,
                                allocator, len, data);
}
void   simu__simu_waveform__free_unpacked
                     (Simu__SimuWaveform *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &simu__simu_waveform__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor simu__simu_settings__field_descriptors[4] =
{
  {
    "tm",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Simu__SimuSettings, tm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hzz",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Simu__SimuSettings, hzz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rps",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Simu__SimuSettings, rps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ms",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Simu__SimuSettings, ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned simu__simu_settings__field_indices_by_name[] = {
  1,   /* field[1] = hzz */
  3,   /* field[3] = ms */
  2,   /* field[2] = rps */
  0,   /* field[0] = tm */
};
static const ProtobufCIntRange simu__simu_settings__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor simu__simu_settings__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "simu.simu_settings",
  "SimuSettings",
  "Simu__SimuSettings",
  "simu",
  sizeof(Simu__SimuSettings),
  4,
  simu__simu_settings__field_descriptors,
  simu__simu_settings__field_indices_by_name,
  1,  simu__simu_settings__number_ranges,
  (ProtobufCMessageInit) simu__simu_settings__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor simu__simu_vitals__field_descriptors[5] =
{
  {
    "tm",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Simu__SimuVitals, tm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v0",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Simu__SimuVitals, v0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v1",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Simu__SimuVitals, v1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v2",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Simu__SimuVitals, v2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v3",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Simu__SimuVitals, v3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned simu__simu_vitals__field_indices_by_name[] = {
  0,   /* field[0] = tm */
  1,   /* field[1] = v0 */
  2,   /* field[2] = v1 */
  3,   /* field[3] = v2 */
  4,   /* field[4] = v3 */
};
static const ProtobufCIntRange simu__simu_vitals__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor simu__simu_vitals__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "simu.simu_vitals",
  "SimuVitals",
  "Simu__SimuVitals",
  "simu",
  sizeof(Simu__SimuVitals),
  5,
  simu__simu_vitals__field_descriptors,
  simu__simu_vitals__field_indices_by_name,
  1,  simu__simu_vitals__number_ranges,
  (ProtobufCMessageInit) simu__simu_vitals__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor simu__simu_waveform__field_descriptors[5] =
{
  {
    "tm",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Simu__SimuWaveform, tm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w0",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Simu__SimuWaveform, n_w0),
    offsetof(Simu__SimuWaveform, w0),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w1",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Simu__SimuWaveform, n_w1),
    offsetof(Simu__SimuWaveform, w1),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w2",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Simu__SimuWaveform, n_w2),
    offsetof(Simu__SimuWaveform, w2),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w3",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Simu__SimuWaveform, n_w3),
    offsetof(Simu__SimuWaveform, w3),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned simu__simu_waveform__field_indices_by_name[] = {
  0,   /* field[0] = tm */
  1,   /* field[1] = w0 */
  2,   /* field[2] = w1 */
  3,   /* field[3] = w2 */
  4,   /* field[4] = w3 */
};
static const ProtobufCIntRange simu__simu_waveform__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor simu__simu_waveform__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "simu.simu_waveform",
  "SimuWaveform",
  "Simu__SimuWaveform",
  "simu",
  sizeof(Simu__SimuWaveform),
  5,
  simu__simu_waveform__field_descriptors,
  simu__simu_waveform__field_indices_by_name,
  1,  simu__simu_waveform__number_ranges,
  (ProtobufCMessageInit) simu__simu_waveform__init,
  NULL,NULL,NULL    /* reserved[123] */
};
