/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: model/dt.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "model/dt.pb-c.h"
void   dt__dt_settings__init
                     (Dt__DtSettings         *message)
{
  static const Dt__DtSettings init_value = DT__DT_SETTINGS__INIT;
  *message = init_value;
}
size_t dt__dt_settings__get_packed_size
                     (const Dt__DtSettings *message)
{
  assert(message->base.descriptor == &dt__dt_settings__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dt__dt_settings__pack
                     (const Dt__DtSettings *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dt__dt_settings__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dt__dt_settings__pack_to_buffer
                     (const Dt__DtSettings *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dt__dt_settings__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dt__DtSettings *
       dt__dt_settings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dt__DtSettings *)
     protobuf_c_message_unpack (&dt__dt_settings__descriptor,
                                allocator, len, data);
}
void   dt__dt_settings__free_unpacked
                     (Dt__DtSettings *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dt__dt_settings__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dt__dt_sensor__init
                     (Dt__DtSensor         *message)
{
  static const Dt__DtSensor init_value = DT__DT_SENSOR__INIT;
  *message = init_value;
}
size_t dt__dt_sensor__get_packed_size
                     (const Dt__DtSensor *message)
{
  assert(message->base.descriptor == &dt__dt_sensor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dt__dt_sensor__pack
                     (const Dt__DtSensor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dt__dt_sensor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dt__dt_sensor__pack_to_buffer
                     (const Dt__DtSensor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dt__dt_sensor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dt__DtSensor *
       dt__dt_sensor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dt__DtSensor *)
     protobuf_c_message_unpack (&dt__dt_sensor__descriptor,
                                allocator, len, data);
}
void   dt__dt_sensor__free_unpacked
                     (Dt__DtSensor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dt__dt_sensor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dt__dt_settings__field_descriptors[4] =
{
  {
    "hzz",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Dt__DtSettings, hzz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rps",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Dt__DtSettings, rps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ms",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Dt__DtSettings, ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "in_mask",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Dt__DtSettings, in_mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dt__dt_settings__field_indices_by_name[] = {
  0,   /* field[0] = hzz */
  3,   /* field[3] = in_mask */
  2,   /* field[2] = ms */
  1,   /* field[1] = rps */
};
static const ProtobufCIntRange dt__dt_settings__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor dt__dt_settings__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dt.dt_settings",
  "DtSettings",
  "Dt__DtSettings",
  "dt",
  sizeof(Dt__DtSettings),
  4,
  dt__dt_settings__field_descriptors,
  dt__dt_settings__field_indices_by_name,
  1,  dt__dt_settings__number_ranges,
  (ProtobufCMessageInit) dt__dt_settings__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dt__dt_sensor__field_descriptors[8] =
{
  {
    "ain0",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Dt__DtSensor, n_ain0),
    offsetof(Dt__DtSensor, ain0),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ain1",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Dt__DtSensor, n_ain1),
    offsetof(Dt__DtSensor, ain1),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ain2",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Dt__DtSensor, n_ain2),
    offsetof(Dt__DtSensor, ain2),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ain3",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Dt__DtSensor, n_ain3),
    offsetof(Dt__DtSensor, ain3),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fio4",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Dt__DtSensor, n_fio4),
    offsetof(Dt__DtSensor, fio4),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fio5",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Dt__DtSensor, n_fio5),
    offsetof(Dt__DtSensor, fio5),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fio6",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Dt__DtSensor, n_fio6),
    offsetof(Dt__DtSensor, fio6),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fio7",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Dt__DtSensor, n_fio7),
    offsetof(Dt__DtSensor, fio7),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dt__dt_sensor__field_indices_by_name[] = {
  0,   /* field[0] = ain0 */
  1,   /* field[1] = ain1 */
  2,   /* field[2] = ain2 */
  3,   /* field[3] = ain3 */
  4,   /* field[4] = fio4 */
  5,   /* field[5] = fio5 */
  6,   /* field[6] = fio6 */
  7,   /* field[7] = fio7 */
};
static const ProtobufCIntRange dt__dt_sensor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor dt__dt_sensor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dt.dt_sensor",
  "DtSensor",
  "Dt__DtSensor",
  "dt",
  sizeof(Dt__DtSensor),
  8,
  dt__dt_sensor__field_descriptors,
  dt__dt_sensor__field_indices_by_name,
  1,  dt__dt_sensor__number_ranges,
  (ProtobufCMessageInit) dt__dt_sensor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
