/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: model/u3.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "model/u3.pb-c.h"
void   u3__u3_settings__init
                     (U3__U3Settings         *message)
{
  static const U3__U3Settings init_value = U3__U3_SETTINGS__INIT;
  *message = init_value;
}
size_t u3__u3_settings__get_packed_size
                     (const U3__U3Settings *message)
{
  assert(message->base.descriptor == &u3__u3_settings__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t u3__u3_settings__pack
                     (const U3__U3Settings *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &u3__u3_settings__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t u3__u3_settings__pack_to_buffer
                     (const U3__U3Settings *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &u3__u3_settings__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
U3__U3Settings *
       u3__u3_settings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (U3__U3Settings *)
     protobuf_c_message_unpack (&u3__u3_settings__descriptor,
                                allocator, len, data);
}
void   u3__u3_settings__free_unpacked
                     (U3__U3Settings *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &u3__u3_settings__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   u3__u3_fsensor__init
                     (U3__U3Fsensor         *message)
{
  static const U3__U3Fsensor init_value = U3__U3_FSENSOR__INIT;
  *message = init_value;
}
size_t u3__u3_fsensor__get_packed_size
                     (const U3__U3Fsensor *message)
{
  assert(message->base.descriptor == &u3__u3_fsensor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t u3__u3_fsensor__pack
                     (const U3__U3Fsensor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &u3__u3_fsensor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t u3__u3_fsensor__pack_to_buffer
                     (const U3__U3Fsensor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &u3__u3_fsensor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
U3__U3Fsensor *
       u3__u3_fsensor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (U3__U3Fsensor *)
     protobuf_c_message_unpack (&u3__u3_fsensor__descriptor,
                                allocator, len, data);
}
void   u3__u3_fsensor__free_unpacked
                     (U3__U3Fsensor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &u3__u3_fsensor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   u3__u3_esensor__init
                     (U3__U3Esensor         *message)
{
  static const U3__U3Esensor init_value = U3__U3_ESENSOR__INIT;
  *message = init_value;
}
size_t u3__u3_esensor__get_packed_size
                     (const U3__U3Esensor *message)
{
  assert(message->base.descriptor == &u3__u3_esensor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t u3__u3_esensor__pack
                     (const U3__U3Esensor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &u3__u3_esensor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t u3__u3_esensor__pack_to_buffer
                     (const U3__U3Esensor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &u3__u3_esensor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
U3__U3Esensor *
       u3__u3_esensor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (U3__U3Esensor *)
     protobuf_c_message_unpack (&u3__u3_esensor__descriptor,
                                allocator, len, data);
}
void   u3__u3_esensor__free_unpacked
                     (U3__U3Esensor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &u3__u3_esensor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor u3__u3_settings__field_descriptors[7] =
{
  {
    "hzz",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(U3__U3Settings, hzz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rps",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(U3__U3Settings, rps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ms",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(U3__U3Settings, ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fin_mask",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(U3__U3Settings, fin_mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ein_mask",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(U3__U3Settings, ein_mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fout_mask",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(U3__U3Settings, fout_mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eout_mask",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(U3__U3Settings, eout_mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned u3__u3_settings__field_indices_by_name[] = {
  4,   /* field[4] = ein_mask */
  6,   /* field[6] = eout_mask */
  3,   /* field[3] = fin_mask */
  5,   /* field[5] = fout_mask */
  0,   /* field[0] = hzz */
  2,   /* field[2] = ms */
  1,   /* field[1] = rps */
};
static const ProtobufCIntRange u3__u3_settings__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor u3__u3_settings__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "u3.u3_settings",
  "U3Settings",
  "U3__U3Settings",
  "u3",
  sizeof(U3__U3Settings),
  7,
  u3__u3_settings__field_descriptors,
  u3__u3_settings__field_indices_by_name,
  1,  u3__u3_settings__number_ranges,
  (ProtobufCMessageInit) u3__u3_settings__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor u3__u3_fsensor__field_descriptors[8] =
{
  {
    "ain0",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(U3__U3Fsensor, n_ain0),
    offsetof(U3__U3Fsensor, ain0),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ain1",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(U3__U3Fsensor, n_ain1),
    offsetof(U3__U3Fsensor, ain1),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ain2",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(U3__U3Fsensor, n_ain2),
    offsetof(U3__U3Fsensor, ain2),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ain3",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(U3__U3Fsensor, n_ain3),
    offsetof(U3__U3Fsensor, ain3),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fio4",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(U3__U3Fsensor, n_fio4),
    offsetof(U3__U3Fsensor, fio4),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fio5",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(U3__U3Fsensor, n_fio5),
    offsetof(U3__U3Fsensor, fio5),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fio6",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(U3__U3Fsensor, n_fio6),
    offsetof(U3__U3Fsensor, fio6),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fio7",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(U3__U3Fsensor, n_fio7),
    offsetof(U3__U3Fsensor, fio7),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned u3__u3_fsensor__field_indices_by_name[] = {
  0,   /* field[0] = ain0 */
  1,   /* field[1] = ain1 */
  2,   /* field[2] = ain2 */
  3,   /* field[3] = ain3 */
  4,   /* field[4] = fio4 */
  5,   /* field[5] = fio5 */
  6,   /* field[6] = fio6 */
  7,   /* field[7] = fio7 */
};
static const ProtobufCIntRange u3__u3_fsensor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor u3__u3_fsensor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "u3.u3_fsensor",
  "U3Fsensor",
  "U3__U3Fsensor",
  "u3",
  sizeof(U3__U3Fsensor),
  8,
  u3__u3_fsensor__field_descriptors,
  u3__u3_fsensor__field_indices_by_name,
  1,  u3__u3_fsensor__number_ranges,
  (ProtobufCMessageInit) u3__u3_fsensor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor u3__u3_esensor__field_descriptors[8] =
{
  {
    "eio0",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(U3__U3Esensor, n_eio0),
    offsetof(U3__U3Esensor, eio0),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eio1",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(U3__U3Esensor, n_eio1),
    offsetof(U3__U3Esensor, eio1),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eio2",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(U3__U3Esensor, n_eio2),
    offsetof(U3__U3Esensor, eio2),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eio3",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(U3__U3Esensor, n_eio3),
    offsetof(U3__U3Esensor, eio3),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eio4",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(U3__U3Esensor, n_eio4),
    offsetof(U3__U3Esensor, eio4),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eio5",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(U3__U3Esensor, n_eio5),
    offsetof(U3__U3Esensor, eio5),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eio6",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(U3__U3Esensor, n_eio6),
    offsetof(U3__U3Esensor, eio6),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eio7",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(U3__U3Esensor, n_eio7),
    offsetof(U3__U3Esensor, eio7),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned u3__u3_esensor__field_indices_by_name[] = {
  0,   /* field[0] = eio0 */
  1,   /* field[1] = eio1 */
  2,   /* field[2] = eio2 */
  3,   /* field[3] = eio3 */
  4,   /* field[4] = eio4 */
  5,   /* field[5] = eio5 */
  6,   /* field[6] = eio6 */
  7,   /* field[7] = eio7 */
};
static const ProtobufCIntRange u3__u3_esensor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor u3__u3_esensor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "u3.u3_esensor",
  "U3Esensor",
  "U3__U3Esensor",
  "u3",
  sizeof(U3__U3Esensor),
  8,
  u3__u3_esensor__field_descriptors,
  u3__u3_esensor__field_indices_by_name,
  1,  u3__u3_esensor__number_ranges,
  (ProtobufCMessageInit) u3__u3_esensor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
