/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PistaDev {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PistaDev(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PistaDev obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_PistaDev(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PistaDev() {
    this(exampleJNI.new_PistaDev(), true);
  }

  public void delSerialIO() {
    exampleJNI.PistaDev_delSerialIO(swigCPtr, this);
  }

  public void setSerialIO(SerialIO cb) {
    exampleJNI.PistaDev_setSerialIO(swigCPtr, this, SerialIO.getCPtr(cb), cb);
  }

  public void send(String buf, int len) {
    exampleJNI.PistaDev_send(swigCPtr, this, buf, len);
  }

}
